function templateRow = buildTemplateSummaryTableRow()
    % BUILDTEMPLATESUMMARYTABLEROW Builds scalar struct containing template row for experiment summary table.
    %
    % AUTHOR: Cole H. Shaigec
    % 
    % OUTPUTS
    %  templateRow struct with fields
    %      .runNumber (double)     
    %      .cmapssSubset (string)
    %      .taskType  (string)   
    %      .windowSize (double)
    %      .warningHorizon (double)
    %      .pcaEnabled (boolean)
    %      .pcaSelectionMode (string)
    %      .pcaVarianceThreshold (double)
    %      .modelName (string)
    %      .hyperparameters_knnK (double)
    %      .hyperparameters_qdaRegularizationStrength (double)
    %      .hyperparameters_naiveBayesVarianceSmoothing (double)
    %      .hyperparameters_randomForestNumTrees (double)
    %      .hyperparameters_randomForestMinLeafSize (double)
    %      .hyperparameters_randomForestNumPredictorsToSample (double)
    %      .hyperparameters_ridgeRegressionLambda (double)
    %      .hyperparameters_weightedRidgeRegressionLambda (double)
    %      .hyperparameters_weightedRidgeRegressionEta (double)
    %      .hyperparameters_weightedRidgeRegressionTau (double)
    %      .mlMetrics_trainAccuracy (double)
    %      .mlMetrics_trainF1 (double)
    %      .mlMetrics_trainPrecision (double)
    %      .mlMetrics_trainRecall (double)
    %      .mlMetrics_trainSpecificity (double)
    %      .mlMetrics_trainBalancedAccuracy (double)
    %      .mlMetrics_trainRMSE (double)
    %      .mlMetrics_trainMAE (double)
    %      .mlMetrics_trainMedAE (double)
    %      .mlMetrics_trainR2 (double)
    %      .mlMetrics_trainBias (double)
    %      .mlMetrics_testAccuracy (double)
    %      .mlMetrics_testF1 (double)
    %      .mlMetrics_testPrecision (double)
    %      .mlMetrics_testRecall (double)
    %      .mlMetrics_testSpecificity (double)
    %      .mlMetrics_testBalancedAccuracy (double)
    %      .mlMetrics_testRMSE (double)
    %      .mlMetrics_testMAE (double)
    %      .mlMetrics_testMedAE (double)
    %      .mlMetrics_testR2 (double)
    %      .mlMetrics_testBias (double)
    %      .errorDiagnostics_classificationNumFalsePositives (nonnegative integer)
    %      .errorDiagnostics_classificationMeanFalsePositiveRUL (double)
    %      .errorDiagnostics_classificationMinFalsePositiveRUL (double)
    %      .errorDiagnostics_classificationMaxFalsePositiveRUL (double)
    %      .errorDiagnostics_classificationNumTruePositives (nonnegative integer)
    %      .errorDiagnostics_classificationMeanTruePositiveRUL (double)
    %      .errorDiagnostics_classificationMinTruePositiveRUL (double)
    %      .errorDiagnostics_classificationMaxTruePositiveRUL (double)
    %      .errorDiagnostics_classificationNumFalseNegatives (nonnegative integer)
    %      .errorDiagnostics_classificationMeanFalseNegativeRUL (double)
    %      .errorDiagnostics_classificationMinFalseNegativeRUL (double)
    %      .errorDiagnostics_classificationMaxFalseNegativeRUL (double)
    %      .errorDiagnostics_regressionNumDangerousMisses (double)
    %      .errorDiagnostics_regressionMeanDangerousMissRUL (double)
    %      .errorDiagnostics_regressionMinDangerousMissRUL (double)
    %      .errorDiagnostics_regressionMaxDangerousMissRUL (double)
    %      .errorDiagnostics_regressionSumDangerousMissRULs (double)
    %      .errorDiagnostics_regressionNumPrematureWarnings (double)
    %      .errorDiagnostics_regressionMeanPrematureWarningRUL (double)
    %      .errorDiagnostics_regressionMinPrematureWarningRUL (double)
    %      .errorDiagnostics_regressionMaxPrematureWarningRUL (double)
    %      .errorDiagnostics_regressionSumPrematureWarningRULs (double)
    %      .costModel_name (string)
    %      .costModel_directMaintenanceCost (positive double)
    %      .costModel_failureCost (positive double)
    %      .costModel_alphaRUL (positive double)
    %      .policyMetrics_totalNumEngines (nonnegative integer)
    %      .policyMetrics_totalMaintenanceJobs (nonnegative integer)
    %      .policyMetrics_numPrematureMaintenanceJobs (nonnegative integer)
    %      .policyMetrics_numTimelyMaintenanceJobs (nonnegative integer)
    %      .policyMetrics_numMissedFailures (nonnegative integer)
    %      .policyMetrics_numCorrectDeferments (nonnegative integer)
    %      .policyMetrics_lostRULFromPrematureMaintenance (nonnegative integer)
    %      .policyCosts_totalDirectMaintenanceCost (double)
    %      .policyCosts_totalFailureCost (double)
    %      .policyCosts_totalPrematureMaintenanceCost (double)
    %      .policyCosts_totalPolicyCost (double)


    % ---------------------------------------------------------------------
    % Type-appropriate placeholders
    % ---------------------------------------------------------------------
    numericPlaceholder  = "";                % For numeric/double fields
    stringPlaceholder   = "";    % For string fields
    logicalPlaceholder  = false;              % For logical/boolean fields

    % ---------------------------------------------------------------------
    % Build template row with fixed schema
    % ---------------------------------------------------------------------
    templateRow = struct( ...
        'runNumber', numericPlaceholder, ...
        'cmapssSubset', stringPlaceholder, ...
        'taskType', stringPlaceholder, ...
        'windowSize', numericPlaceholder, ...
        'warningHorizon', numericPlaceholder, ...
        'pcaEnabled', logicalPlaceholder, ...
        'pcaSelectionMode', stringPlaceholder, ...
        'pcaVarianceThreshold', numericPlaceholder, ...
        'modelName', stringPlaceholder, ...
        'hyperparameters_knnK', numericPlaceholder, ...
        'hyperparameters_qdaRegularizationStrength', numericPlaceholder, ...
        'hyperparameters_naiveBayesVarianceSmoothing', numericPlaceholder, ...
        'hyperparameters_randomForestNumTrees', numericPlaceholder, ...
        'hyperparameters_randomForestMinLeafSize', numericPlaceholder, ...
        'hyperparameters_randomForestNumPredictorsToSample', numericPlaceholder, ...
        'hyperparameters_ridgeRegressionLambda', numericPlaceholder, ...
        'hyperparameters_weightedRidgeRegressionLambda', numericPlaceholder, ...
        'hyperparameters_weightedRidgeRegressionEta', numericPlaceholder, ...
        'hyperparameters_weightedRidgeRegressionTau', numericPlaceholder, ...
        'mlMetrics_trainAccuracy', numericPlaceholder, ...
        'mlMetrics_trainF1', numericPlaceholder, ...
        'mlMetrics_trainPrecision', numericPlaceholder, ...
        'mlMetrics_trainRecall', numericPlaceholder, ...
        'mlMetrics_trainSpecificity', numericPlaceholder, ...
        'mlMetrics_trainBalancedAccuracy', numericPlaceholder, ...
        'mlMetrics_trainRMSE', numericPlaceholder, ...
        'mlMetrics_trainMAE', numericPlaceholder, ...
        'mlMetrics_trainMedAE', numericPlaceholder, ...
        'mlMetrics_trainR2', numericPlaceholder, ...
        'mlMetrics_trainBias', numericPlaceholder, ...
        'mlMetrics_testAccuracy', numericPlaceholder, ...
        'mlMetrics_testF1', numericPlaceholder, ...
        'mlMetrics_testPrecision', numericPlaceholder, ...
        'mlMetrics_testRecall', numericPlaceholder, ...
        'mlMetrics_testSpecificity', numericPlaceholder, ...
        'mlMetrics_testBalancedAccuracy', numericPlaceholder, ...
        'mlMetrics_testRMSE', numericPlaceholder, ...
        'mlMetrics_testMAE', numericPlaceholder, ...
        'mlMetrics_testMedAE', numericPlaceholder, ...
        'mlMetrics_testR2', numericPlaceholder, ...
        'mlMetrics_testBias', numericPlaceholder, ...
        'errorDiagnostics_classificationNumFalsePositives', numericPlaceholder, ...
        'errorDiagnostics_classificationMeanFalsePositiveRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationMinFalsePositiveRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationMaxFalsePositiveRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationNumTruePositives', numericPlaceholder, ...
        'errorDiagnostics_classificationMeanTruePositiveRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationMinTruePositiveRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationMaxTruePositiveRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationNumFalseNegatives', numericPlaceholder, ...
        'errorDiagnostics_classificationMeanFalseNegativeRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationMinFalseNegativeRUL', numericPlaceholder, ...
        'errorDiagnostics_classificationMaxFalseNegativeRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionNumDangerousMisses', numericPlaceholder, ...
        'errorDiagnostics_regressionMeanDangerousMissRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionMinDangerousMissRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionMaxDangerousMissRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionSumDangerousMissRULs', numericPlaceholder, ...
        'errorDiagnostics_regressionNumPrematureWarnings', numericPlaceholder, ...
        'errorDiagnostics_regressionMeanPrematureWarningRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionMinPrematureWarningRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionMaxPrematureWarningRUL', numericPlaceholder, ...
        'errorDiagnostics_regressionSumPrematureWarningRULs', numericPlaceholder, ...
        'costModel_name', stringPlaceholder, ...
        'costModel_directMaintenanceCost', numericPlaceholder, ...
        'costModel_failureCost', numericPlaceholder, ...
        'costModel_alphaRUL', numericPlaceholder, ...
        'policyMetrics_totalNumEngines', numericPlaceholder, ...
        'policyMetrics_totalMaintenanceJobs', numericPlaceholder, ...
        'policyMetrics_numPrematureMaintenanceJobs', numericPlaceholder, ...
        'policyMetrics_numTimelyMaintenanceJobs', numericPlaceholder, ...
        'policyMetrics_numMissedFailures', numericPlaceholder, ...
        'policyMetrics_numCorrectDeferments', numericPlaceholder, ...
        'policyMetrics_lostRULFromPrematureMaintenance', numericPlaceholder, ...
        'policyCosts_totalDirectMaintenanceCost', numericPlaceholder, ...
        'policyCosts_totalFailureCost', numericPlaceholder, ...
        'policyCosts_totalPrematureMaintenanceCost', numericPlaceholder, ...
        'policyCosts_totalPolicyCost', numericPlaceholder ...
    );
end