function validateModelSpec(modelSpec, modelSpecIndex)
    % VALIDATEMODELSPEC Validates a single model specification.

    assert(isstruct(modelSpec) && isscalar(modelSpec), ...
        'Each modelSpec must be a scalar struct. Failed at index %d.', ...
        modelSpecIndex);

    requiredFields = {'modelName', 'hyperparameterGrid'};
    missingFields = requiredFields(~isfield(modelSpec, requiredFields));

    assert(isempty(missingFields), ...
        'modelSpec at index %d is missing required field(s): %s.', ...
        modelSpecIndex, strjoin(missingFields, ', '));

    modelName = string(modelSpec.modelName);
    assert(isscalar(modelName) && strlength(modelName) > 0, ...
        'modelSpec(%d).modelName must be a nonempty string scalar or char vector.', ...
        modelSpecIndex);

    assert(isstruct(modelSpec.hyperparameterGrid) && isscalar(modelSpec.hyperparameterGrid), ...
        'modelSpec(%d).hyperparameterGrid must be a scalar struct.', ...
        modelSpecIndex);
end