function experimentSpec = buildExperimentSpec()
    % BUILDEXPERIMENTSPEC Defines plan of experimentation.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % OUTPUT
    %  experimentSpec struct with fields
    %      .modelSpecs (array of modelSpec structs)
    %      .pcaSpecs   (array of pcaSpec structs)
    %      .warningHorizons (nonempty cell array; each cell contains a positive numeric vector)
    %      .cmapssSubsets (nonempty cell array of subset names: 'FD001', 'FD002', 'FD003', or 'FD004')
    %      .windowSizes (array of positive integers)
    %      .numFolds (positive integer)
    %
    % NOTES
    % - This function is the source of truth for defining the
    % experimentation plan. To change the scope of experimentation, change
    % the hard-coded parameters in this file. 

    %%%%%%%%%%%%%%%%%%%%%%%%%
    % FINAL RUN DESIGN NOTE %
    %%%%%%%%%%%%%%%%%%%%%%%%%
    % This experimentSpec is hypothesis-driven, not leaderboard-driven.
    %
    % It supports the following reportable questions:
    %  1. Warning horizon sensitivity.
    %  2. Ridge vs weighted ridge decision-value comparison.
    %  3. Classification vs regression framing.
    %  4. FD001 vs FD003 robustness.
    %  5. PCA/no-PCA dimensionality-reduction effects.
    %  6. Temporal history-window effects.
    %  7. Error-type economics through downstream policy analysis.
    %
    % kNN is deliberately excluded from this final run because it is too slow
    % relative to its expected project value. Run kNN separately if needed.

    % -- Add models --
    numberOfModelsToAnalyze = 1;
    modelSpecs = repmat(buildTemplateModelSpecStruct(), numberOfModelsToAnalyze, 1);

    % modelSpecs(1) = struct( ...
    %     'modelName', 'naiveBayes', ...
    %     'hyperparameterGrid', struct('varianceSmoothing', 0.1:0.1:0.5) ...
    % );
    % 
    % modelSpecs(2) = struct( ...
    %     'modelName', 'QDA', ...
    %     'hyperparameterGrid', struct( ...
    %         'regularizationStrength', [0.001, 0.01, 0.05, 0.1, 0.5, 1.0] ...
    %     ) ...
    % );
    % % 
    modelSpecs(1) = struct( ...
        'modelName', 'randomForest', ...
        'hyperparameterGrid', struct( ...
            'numTrees', [10, 25, 50, 75], ...
            'minLeafSize', [5, 10, 15, 20], ...
            'numPredictorsToSample', [1, 3, 5] ...
        ) ...
    );

    % modelSpecs(1) = struct( ...
    %     'modelName', 'ridgeRegression', ...
    %     'hyperparameterGrid', struct( ...
    %         'lambda', logspace(-3, 3, 7) ...
    %     ) ...
    % );

    % modelSpecs(2) = struct( ...
    %     'modelName', 'weightedRidgeRegression', ...
    %     'hyperparameterGrid', struct( ...
    %         'lambda', logspace(-4, 4, 9), ...
    %         'eta', [0.25, 0.5, 1.0, 2.0], ...
    %         'tau', [0.5, 1.0, 2.0, 4.0] ...
    %     ) ...
    % );

    % -- Add PCA --
    numPCAScenarios = 1;
    pcaSpecs = repmat(buildTemplatePCASpecStruct(), numPCAScenarios, 1);

    % Baseline: preserve original feature space.
    pcaSpecs(1) = struct( ...
        'enabled', false, ...
        'selectionMode', 'varianceThreshold', ...
        'varianceThreshold', 0.95, ...
        'fixedNumComponents', 0 ...
    );

    % % Variance-preserving PCA.
    % pcaSpecs(2) = struct( ...
    %     'enabled', true, ...
    %     'selectionMode', 'varianceThreshold', ...
    %     'varianceThreshold', 0.95, ...
    %     'fixedNumComponents', 0 ...
    % );
    % 
    % % Aggressive fixed-dimensional PCA.
    % pcaSpecs(3) = struct( ...
    %     'enabled', true, ...
    %     'selectionMode', 'fixedNumComponents', ...
    %     'varianceThreshold', 0, ...
    %     'fixedNumComponents', 4 ...
    % );

    % -- Add warning horizons --
    warningHorizons = num2cell(1:2:150);

    % -- Choose CMAPSS subsets --
    cmapssSubsets = {'FD001', 'FD003'};

    % -- Choose window sizes --
    windowSizes = [1, 3, 5, 7];

    % -- Set cross-validation fold policy --
    numFolds = 5;

    % -- Populate output struct --
    experimentSpec = struct();
    experimentSpec.modelSpecs = modelSpecs;
    experimentSpec.pcaSpecs = pcaSpecs;
    experimentSpec.warningHorizons = warningHorizons;
    experimentSpec.cmapssSubsets = cmapssSubsets;
    experimentSpec.windowSizes = windowSizes;
    experimentSpec.numFolds = numFolds;

    % -- Validate experimentSpec --
    validateExperimentSpec(experimentSpec);

end