function experimentSpec = buildExperimentSpec()
    % BUILDEXPERIMENTSPEC Defines plan of experimentation.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % OUTPUT
    %  experimentSpec struct with fields
    %      .modelSpecs (array of modelSpec structs)
    %      .pcaSpecs   (array of pcaSpec structs)
    %      .warningHorizons (nonempty cell array; each cell contains a positive numeric vector)
    %      .cmapssSubsets (nonempty cell array of subset names: 'FD001', 'FD002', 'FD003', or 'FD004')
    %      .windowSizes (array of positive integers)
    %      .numFolds (positive integer)
    %
    % NOTES
    % - This function is the source of truth for defining the
    % experimentation plan. To change the scope of experimentation, change
    % the hard-coded parameters in this file. 

    % -- Add models --
    numberOfModelsToAnalyze = 1; % must equal the number of models below
    modelSpecs = repmat(buildTemplateModelSpecStruct(), numberOfModelsToAnalyze, 1);
    
    modelSpecs(1) = struct( ...
        'modelName', 'kNN', ...
        'hyperparameterGrid', struct( ...
             'k', 3 ...
         ) ...
    );
    %   modelSpecs(1) = struct( ...
    %     'modelName', 'QDA', ...
    %     'hyperparameterGrid', struct( ...
    %          'regularizationStrength', [0.2,0.4] ...
    %      ) ...
    % );
    % 
    % modelSpecs(1) = struct( ...
    %     'modelName', 'randomForest', ...
    %     'hyperparameterGrid', struct( ...
    %          'numTrees', 1:3, ...
    %          'minLeafSize', 1:2, ...
    %          'numPredictorsToSample', 1 ...
    %      ) ...
    % );
    % % 
    % modelSpecs(1) = struct( ...
    %     'modelName', 'ridgeRegression', ...
    %     'hyperparameterGrid', struct( ...
    %          'lambda', logspace(-4, 4, 5) ...
    %      ) ...
    % );
    % % 
    % modelSpecs(2) = struct( ...
    %     'modelName', 'weightedRidgeRegression', ...
    %     'hyperparameterGrid', struct( ...
    %          'lambda', logspace(-4, 4, 5), ...
    %          'eta', [0.25, 0.5, 1.0], ...
    %          'tau', [0.5, 1.0, 2.0] ...
    %      ) ...
    % );

    % -- Add PCA -- 
    numPCAScenarios = 3;
    pcaSpecs = repmat(buildTemplatePCASpecStruct(), numPCAScenarios, 1);

    pcaSpecs(1) = struct( ...
        'enabled', true, ...
        'selectionMode', 'varianceThreshold', ...
        'varianceThreshold', 0.95, ...
        'fixedNumComponents', 0 ...
    );

    pcaSpecs(2) = struct( ...
        'enabled', true, ...
        'selectionMode', 'fixedNumComponents', ...
        'varianceThreshold', 0, ...
        'fixedNumComponents', 4 ...
    );

    pcaSpecs(3) = struct( ...
        'enabled', false, ...
        'selectionMode', 'varianceThreshold', ...
        'varianceThreshold', 0.95, ...
        'fixedNumComponents', 0 ...
    );

    % -- Add warning horizons --
    warningHorizons = num2cell(12);

    % -- Choose CMAPSS subsets -- 
    cmapssSubsets = {'FD001'};

    % -- Choose window sizes --
    windowSizes = 1:1:5;

    % -- Set cross-validation fold policy --
    numFolds = 5;

    % -- Populate output struct --
    experimentSpec = struct();
    experimentSpec.modelSpecs = modelSpecs;
    experimentSpec.pcaSpecs = pcaSpecs;
    experimentSpec.warningHorizons = warningHorizons;
    experimentSpec.cmapssSubsets = cmapssSubsets;
    experimentSpec.windowSizes = windowSizes;
    experimentSpec.numFolds = numFolds;

    % -- Validate experimentSpec --
    validateExperimentSpec(experimentSpec);
end