function pipelineQueue = generateRunSpecsFromExperimentSpec(experimentSpec)
    %   GENERATERUNSPECSFROMEXPERIMENTSPEC(EXPERIMENTSPEC) Decompose
    %   validated experimentSpec into atomic pipeline runs.
    %   Returns: pipelineQueue (array of singleRunSpec structs)


    %%%%%%%%%%%%%%%%%%%%%%%%
    %%%% IMPORTANT NOTE %%%%
    %%%%%%%%%%%%%%%%%%%%%%%%
    % THIS FUNCTION SHOULD BE TREATED AS THE SOURCE OF TRUTH FOR STRUCTS!
    % ALL OPTIONS STRUCTS & VALIDATORS IN THE CODEBASE MUST FOLLOW THE FORMAT BELOW!


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %  Generate indices for option extraction  %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    idxWarningHorizons = 1:numel(experimentSpec.warningHorizons);
    idxPCAOptions = 1:numel(experimentSpec.pcaOptions);
    idxModelOptions = 1:numel(experimentSpec.modelOptions);
    idxDatasetOptions = 1:numel(experimentSpec.datasetOptions);
    
    % Construct experiment indices as Cartesian product of option struct
    % indices
    experimentIndices = combinations( ...
        idxWarningHorizons, ...
        idxPCAOptions, ...
        idxModelOptions, ...
        idxDatasetOptions ...
    );

    numPipelineRunsNeeded = height(experimentIndices);
    experimentIndices = table2array(experimentIndices);

    % Construct template struct and preallocate pipeline queue
    templatePCASpec = struct( ...
        'enabled', true, ...
        'varianceThreshold', 0.95 ...
    );

    % NOTE: spec structs for model and dataset not yet designed!
    templateSingleRunSpec = struct( ...
        'id', 0, ...
        'experimentKey', 0, ...
        'warningHorizon', 0, ...
        'pcaSpec', templatePCASpec, ...
        'modelSpec', struct(), ...
        'datasetSpec', struct() ...
    );    
  
    % Preallocate pipeline queue
    pipelineQueue = repmat(templateSingleRunSpec, 1, numPipelineRunsNeeded);

    for i = 1 : numPipelineRunsNeeded
        runIndices = experimentIndices(i,:);

        pipelineQueue(i) = struct( ...
            'id', i, ...
            'experimentKey', experimentSpec.id, ...
            'warningHorizon', experimentSpec.warningHorizons(runIndices(1)),...
            'pcaSpec', experimentSpec.pcaOptions(runIndices(4)),...
            'modelSpec', experimentSpec.modelOptions(runIndices(6)),...
            'datasetSpec', experimentSpec.datasetOptions(runIndices(7))...
        );
    end

end