function pipelineQueue = generateRunSpecsFromExperimentSpec(experimentSpec)
    %   GENERATERUNSPECSFROMEXPERIMENTSPEC(EXPERIMENTSPEC) Decompose
    %   validated experimentSpec into atomic pipeline runs.
    %   Returns: pipelineQueue (array of singleRunSpec structs)


    %%%%%%%%%%%%%%%%%%%%%%%%
    %%%% IMPORTANT NOTE %%%%
    %%%%%%%%%%%%%%%%%%%%%%%%
    % THIS FUNCTION SHOULD BE TREATED AS THE SOURCE OF TRUTH FOR STRUCTS!
    % ALL OPTIONS STRUCTS & VALIDATORS IN THE CODEBASE MUST FOLLOW THE FORMAT BELOW!


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %  Generate indices for option extraction  %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    idxWarningHorizons = 1:numel(experimentSpec.warningHorizons);
    idxNoiseOptions = 1:numel(experimentSpec.noiseOptions);
    idxPCAOptions = 1:numel(experimentSpec.pcaOptions);
    idxImbalanceOptions = 1:numel(experimentSpec.imbalanceOptions);
    idxModelOptions = 1:numel(experimentSpec.modelOptions);
    idxDatasetOptions = 1:numel(experimentSpec.datasetOptions);
    
    % Construct experiment indices as Cartesian product of option struct
    % indices
    experimentIndices = combinations( ...
        idxWarningHorizons, ...
        idxNoiseOptions, ...
        idxPCAOptions, ...
        idxImbalanceOptions, ...
        idxModelOptions, ...
        idxDatasetOptions ...
    );

    numPipelineRunsNeeded = height(experimentIndices);
    experimentIndices = table2array(experimentIndices);

    % Construct template struct and preallocate pipeline queue

    %%% NOTE: impulseNoiseSpec not yet designed
    templateNoiseSpec = struct( ...
        'enabled', false, ...
        'noiseType', 'gaussian', ...
        'gaussianNoiseSpec', struct( ...
            'dimension', 1, ...
            'mean', 0, ...
            'covariance', 1 ...
            ), ...
        'impulseNoiseSpec', struct() ... 
    );

    templatePCASpec = struct( ...
        'enabled', true, ...
        'varianceThreshold', 0.95 ...
    );

    % NOTE: spec structs for imbalance, model, and dataset not yet designed!
    templateSingleRunSpec = struct( ...
        'id', 0, ...
        'experimentKey', 0, ...
        'warningHorizon', 0, ...
        'noiseSpec', templateNoiseSpec, ...
        'pcaSpec', templatePCASpec, ...
        'imbalanceSpec', struct(), ...
        'modelSpec', struct(), ...
        'datasetSpec', struct() ...
    );    
  
    % Preallocate pipeline queue
    pipelineQueue = repmat(templateSingleRunSpec, 1, numPipelineRunsNeeded);

    for i = 1 : numPipelineRunsNeeded
        runIndices = experimentIndices(i,:);

        pipelineQueue(i) = struct( ...
            'id', i, ...
            'experimentKey', experimentSpec.id, ...
            'warningHorizon', experimentSpec.warningHorizons(runIndices(1)),...
            'noiseSpec', experimentSpec.noiseOptions(runIndices(2)),...
            'pcaSpec', experimentSpec.pcaOptions(runIndices(4)),...
            'imbalanceSpec', experimentSpec.imbalanceOptions(runIndices(5)),...
            'modelSpec', experimentSpec.modelOptions(runIndices(6)),...
            'datasetSpec', experimentSpec.datasetOptions(runIndices(7))...
        );
    end

end