function validateRandomForestResult(randomForestResult, dataset, randomForestModel)
% VALIDATERANDOMFORESTRESULT Validates random forest prediction result struct.
%
% INPUTS
%  randomForestResult (struct)
%  dataset (struct)
%  randomForestModel (struct)
%
% OUTPUTS
%  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(randomForestResult), ...
        'validateRandomForestResult:ResultMustBeStruct', ...
        'randomForestResult must be a struct.');

    assert(isstruct(dataset), ...
        'validateRandomForestResult:DatasetMustBeStruct', ...
        'dataset must be a struct.');

    assert(isstruct(randomForestModel), ...
        'validateRandomForestResult:ModelMustBeStruct', ...
        'randomForestModel must be a struct.');

    %---------------------------%
    % dataset validation        %
    %---------------------------%
    requiredDatasetFields = {'X', 'y'};
    assert(all(isfield(dataset, requiredDatasetFields)), ...
        'validateRandomForestResult:MissingDatasetFields', ...
        'dataset must contain fields: X and y.');

    X = dataset.X;
    y = dataset.y;

    assert(isnumeric(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateRandomForestResult:InvalidDatasetX', ...
        'dataset.X must be a finite full double matrix.');

    assert(isnumeric(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateRandomForestResult:InvalidDatasetY', ...
        'dataset.y must be a finite full double column vector.');

    n = size(X, 1);
    d = size(X, 2);

    assert(size(y, 1) == n, ...
        'validateRandomForestResult:DatasetDimensionMismatch', ...
        'dataset.X and dataset.y must have the same number of rows.');

    assert(d >= 1, ...
        'validateRandomForestResult:EmptyFeatureDimension', ...
        'dataset.X must contain at least one feature column.');

    %---------------------------%
    % model validation          %
    %---------------------------%
    requiredModelFields = {'ensemble', 'numTrees', 'minLeafSize', 'numPredictorsToSample'};
    assert(all(isfield(randomForestModel, requiredModelFields)), ...
        'validateRandomForestResult:MissingModelFields', ...
        ['randomForestModel must contain fields: ensemble, numTrees, ' ...
         'minLeafSize, numPredictorsToSample.']);

    ensemble = randomForestModel.ensemble;
    modelNumTrees = randomForestModel.numTrees;
    modelMinLeafSize = randomForestModel.minLeafSize;
    modelNumPredictorsToSample = randomForestModel.numPredictorsToSample;

    assert(~isempty(ensemble), ...
        'validateRandomForestResult:EmptyEnsemble', ...
        'randomForestModel.ensemble must be nonempty.');

    assert(contains(class(ensemble), 'ClassificationEnsemble'), ...
    'validateRandomForestModel:InvalidEnsembleClass', ...
    ['randomForestModel.ensemble must be a MATLAB classification ensemble. ' ...
     'Actual class was: %s.'], class(ensemble));

    assert(isnumeric(modelNumTrees) && isscalar(modelNumTrees) && isreal(modelNumTrees) && ...
        isfinite(modelNumTrees) && (modelNumTrees == floor(modelNumTrees)) && ...
        (modelNumTrees > 0), ...
        'validateRandomForestResult:InvalidModelNumTrees', ...
        'randomForestModel.numTrees must be a positive integer.');

    assert(isnumeric(modelMinLeafSize) && isscalar(modelMinLeafSize) && isreal(modelMinLeafSize) && ...
        isfinite(modelMinLeafSize) && (modelMinLeafSize == floor(modelMinLeafSize)) && ...
        (modelMinLeafSize > 0), ...
        'validateRandomForestResult:InvalidModelMinLeafSize', ...
        'randomForestModel.minLeafSize must be a positive integer.');

    assert(isnumeric(modelNumPredictorsToSample) && isscalar(modelNumPredictorsToSample) && ...
        isreal(modelNumPredictorsToSample) && isfinite(modelNumPredictorsToSample) && ...
        (modelNumPredictorsToSample == floor(modelNumPredictorsToSample)) && ...
        (modelNumPredictorsToSample > 0), ...
        'validateRandomForestResult:InvalidModelNumPredictorsToSample', ...
        'randomForestModel.numPredictorsToSample must be a positive integer.');

    assert(modelNumPredictorsToSample <= d, ...
        'validateRandomForestResult:ModelNumPredictorsToSampleTooLarge', ...
        'randomForestModel.numPredictorsToSample must not exceed size(dataset.X, 2).');

    %---------------------------%
    % result field validation   %
    %---------------------------%
    requiredResultFields = {'yHat', 'metadata'};
    assert(all(isfield(randomForestResult, requiredResultFields)), ...
        'validateRandomForestResult:MissingResultFields', ...
        'randomForestResult must contain fields: yHat and metadata.');

    yHat = randomForestResult.yHat;
    metadata = randomForestResult.metadata;

    assert(isnumeric(yHat) && iscolumn(yHat) && ~issparse(yHat) && all(isfinite(yHat)), ...
        'validateRandomForestResult:InvalidYHat', ...
        'randomForestResult.yHat must be a finite full double column vector.');

    assert(size(yHat, 1) == n, ...
        'validateRandomForestResult:YHatSizeMismatch', ...
        'randomForestResult.yHat must have size n x 1 where n = size(dataset.X, 1).');

    % Optional but useful: enforce binary-label compatibility if that is the project invariant
    allowedLabels = unique(dataset.y);
    assert(all(ismember(yHat, allowedLabels)), ...
        'validateRandomForestResult:PredictedLabelsNotInDatasetLabelSet', ...
        ['All entries of randomForestResult.yHat must belong to the label set ' ...
         'present in dataset.y.']);

    assert(isstruct(metadata) && isscalar(metadata), ...
        'validateRandomForestResult:InvalidMetadata', ...
        'randomForestResult.metadata must be a scalar struct.');

    %---------------------------%
    % metadata validation       %
    %---------------------------%
    requiredMetadataFields = {'numTrees', 'minLeafSize', 'numPredictorsToSample'};
    assert(all(isfield(metadata, requiredMetadataFields)), ...
        'validateRandomForestResult:MissingMetadataFields', ...
        ['randomForestResult.metadata must contain fields: numTrees, ' ...
         'minLeafSize, numPredictorsToSample.']);

    metadataNumTrees = metadata.numTrees;
    metadataMinLeafSize = metadata.minLeafSize;
    metadataNumPredictorsToSample = metadata.numPredictorsToSample;

    assert(isnumeric(metadataNumTrees) && isscalar(metadataNumTrees) && isreal(metadataNumTrees) && ...
        isfinite(metadataNumTrees) && (metadataNumTrees == floor(metadataNumTrees)) && ...
        (metadataNumTrees > 0), ...
        'validateRandomForestResult:InvalidMetadataNumTrees', ...
        'metadata.numTrees must be a positive integer.');

    assert(isnumeric(metadataMinLeafSize) && isscalar(metadataMinLeafSize) && isreal(metadataMinLeafSize) && ...
        isfinite(metadataMinLeafSize) && (metadataMinLeafSize == floor(metadataMinLeafSize)) && ...
        (metadataMinLeafSize > 0), ...
        'validateRandomForestResult:InvalidMetadataMinLeafSize', ...
        'metadata.minLeafSize must be a positive integer.');

    assert(isnumeric(metadataNumPredictorsToSample) && isscalar(metadataNumPredictorsToSample) && ...
        isreal(metadataNumPredictorsToSample) && isfinite(metadataNumPredictorsToSample) && ...
        (metadataNumPredictorsToSample == floor(metadataNumPredictorsToSample)) && ...
        (metadataNumPredictorsToSample > 0), ...
        'validateRandomForestResult:InvalidMetadataNumPredictorsToSample', ...
        'metadata.numPredictorsToSample must be a positive integer.');

    assert(metadataNumPredictorsToSample <= d, ...
        'validateRandomForestResult:MetadataNumPredictorsToSampleTooLarge', ...
        'metadata.numPredictorsToSample must not exceed size(dataset.X, 2).');

    %--------------------------------------%
    % Metadata / model consistency checks  %
    %--------------------------------------%
    assert(metadataNumTrees == modelNumTrees, ...
        'validateRandomForestResult:MetadataNumTreesMismatch', ...
        'metadata.numTrees must match randomForestModel.numTrees.');

    assert(metadataMinLeafSize == modelMinLeafSize, ...
        'validateRandomForestResult:MetadataMinLeafSizeMismatch', ...
        'metadata.minLeafSize must match randomForestModel.minLeafSize.');

    assert(metadataNumPredictorsToSample == modelNumPredictorsToSample, ...
        'validateRandomForestResult:MetadataNumPredictorsToSampleMismatch', ...
        ['metadata.numPredictorsToSample must match ' ...
         'randomForestModel.numPredictorsToSample.']);

    %--------------------------------------%
    % Ensemble prediction interface sanity %
    %--------------------------------------%
    try
        yHatProbe = predict(ensemble, X);
    catch ME
        error('validateRandomForestResult:EnsemblePredictionFailed', ...
            ['randomForestModel.ensemble failed predict(X) on dataset.X. ' ...
             'Original error: %s'], ME.message);
    end

    isSupportedPredictOutput = ...
        isnumeric(yHatProbe) || islogical(yHatProbe) || iscategorical(yHatProbe) || ...
        isstring(yHatProbe) || ischar(yHatProbe) || iscellstr(yHatProbe);

    assert(isSupportedPredictOutput, ...
        'validateRandomForestResult:UnsupportedPredictOutputType', ...
        ['predict(randomForestModel.ensemble, dataset.X) returned an unsupported ' ...
         'output type for class labels.']);

    assert(numel(yHatProbe) == n, ...
        'validateRandomForestResult:PredictOutputSizeMismatch', ...
        'predict(randomForestModel.ensemble, dataset.X) must return n predicted labels.');

end