function validateRandomForestModel(randomForestModel, trainingData, randomForestHyperparameters)
% VALIDATERANDOMFORESTMODEL Validates trained random forest model struct.
%
% INPUTS
%  randomForestModel (struct)
%  trainingData (struct)
%  randomForestHyperparameters (struct)
%
% OUTPUTS
%  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(randomForestModel), ...
        'validateRandomForestModel:ModelMustBeStruct', ...
        'randomForestModel must be a struct.');

    assert(isstruct(trainingData), ...
        'validateRandomForestModel:TrainingDataMustBeStruct', ...
        'trainingData must be a struct.');

    assert(isstruct(randomForestHyperparameters), ...
        'validateRandomForestModel:HyperparametersMustBeStruct', ...
        'randomForestHyperparameters must be a struct.');

    %---------------------------%
    % trainingData validation   %
    %---------------------------%
    requiredTrainingFields = {'X', 'y'};
    assert(all(isfield(trainingData, requiredTrainingFields)), ...
        'validateRandomForestModel:MissingTrainingDataFields', ...
        'trainingData must contain fields: X and y.');

    X = trainingData.X;
    y = trainingData.y;

    assert(isnumeric(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateRandomForestModel:InvalidTrainingX', ...
        'trainingData.X must be a finite full double matrix.');

    assert(isnumeric(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateRandomForestModel:InvalidTrainingY', ...
        'trainingData.y must be a finite full double column vector.');

    nTrain = size(X, 1);
    d = size(X, 2);

    assert(size(y, 1) == nTrain, ...
        'validateRandomForestModel:TrainingDimensionMismatch', ...
        'trainingData.X and trainingData.y must have the same number of rows.');

    assert(d >= 1, ...
        'validateRandomForestModel:EmptyFeatureDimension', ...
        'trainingData.X must contain at least one feature column.');

    %--------------------------------------%
    % Hyperparameter struct field checking %
    %--------------------------------------%
    requiredHyperparameterFields = {'numTrees', 'minLeafSize', 'numPredictorsToSample'};
    assert(all(isfield(randomForestHyperparameters, requiredHyperparameterFields)), ...
        'validateRandomForestModel:MissingHyperparameterFields', ...
        ['randomForestHyperparameters must contain fields: ' ...
         'numTrees, minLeafSize, numPredictorsToSample.']);

    numTrees = randomForestHyperparameters.numTrees;
    minLeafSize = randomForestHyperparameters.minLeafSize;
    numPredictorsToSample = randomForestHyperparameters.numPredictorsToSample;

    assert(isnumeric(numTrees) && isscalar(numTrees) && isreal(numTrees) && ...
        isfinite(numTrees) && (numTrees == floor(numTrees)) && (numTrees > 0), ...
        'validateRandomForestModel:InvalidNumTrees', ...
        'randomForestHyperparameters.numTrees must be a positive integer.');

    assert(isnumeric(minLeafSize) && isscalar(minLeafSize) && isreal(minLeafSize) && ...
        isfinite(minLeafSize) && (minLeafSize == floor(minLeafSize)) && (minLeafSize > 0), ...
        'validateRandomForestModel:InvalidMinLeafSize', ...
        'randomForestHyperparameters.minLeafSize must be a positive integer.');

    assert(isnumeric(numPredictorsToSample) && isscalar(numPredictorsToSample) && ...
        isreal(numPredictorsToSample) && isfinite(numPredictorsToSample) && ...
        (numPredictorsToSample == floor(numPredictorsToSample)) && ...
        (numPredictorsToSample > 0), ...
        'validateRandomForestModel:InvalidNumPredictorsToSample', ...
        'randomForestHyperparameters.numPredictorsToSample must be a positive integer.');

    assert(numPredictorsToSample <= d, ...
        'validateRandomForestModel:NumPredictorsToSampleTooLarge', ...
        ['randomForestHyperparameters.numPredictorsToSample must not exceed ' ...
         'size(trainingData.X, 2).']);

    %---------------------------%
    % Model field validation    %
    %---------------------------%
    requiredModelFields = {'ensemble', 'numTrees', 'minLeafSize', 'numPredictorsToSample'};
    assert(all(isfield(randomForestModel, requiredModelFields)), ...
        'validateRandomForestModel:MissingModelFields', ...
        ['randomForestModel must contain fields: ensemble, numTrees, ' ...
         'minLeafSize, numPredictorsToSample.']);

    ensemble = randomForestModel.ensemble;
    modelNumTrees = randomForestModel.numTrees;
    modelMinLeafSize = randomForestModel.minLeafSize;
    modelNumPredictorsToSample = randomForestModel.numPredictorsToSample;

    assert(~isempty(ensemble), ...
        'validateRandomForestModel:EmptyEnsemble', ...
        'randomForestModel.ensemble must be nonempty.');

    assert(contains(class(ensemble), 'ClassificationEnsemble'), ...
    'validateRandomForestModel:InvalidEnsembleClass', ...
    ['randomForestModel.ensemble must be a MATLAB classification ensemble. ' ...
     'Actual class was: %s.'], class(ensemble));

    assert(isnumeric(modelNumTrees) && isscalar(modelNumTrees) && isreal(modelNumTrees) && ...
        isfinite(modelNumTrees) && (modelNumTrees == floor(modelNumTrees)) && ...
        (modelNumTrees > 0), ...
        'validateRandomForestModel:InvalidModelNumTrees', ...
        'randomForestModel.numTrees must be a positive integer.');

    assert(isnumeric(modelMinLeafSize) && isscalar(modelMinLeafSize) && isreal(modelMinLeafSize) && ...
        isfinite(modelMinLeafSize) && (modelMinLeafSize == floor(modelMinLeafSize)) && ...
        (modelMinLeafSize > 0), ...
        'validateRandomForestModel:InvalidModelMinLeafSize', ...
        'randomForestModel.minLeafSize must be a positive integer.');

    assert(isnumeric(modelNumPredictorsToSample) && isscalar(modelNumPredictorsToSample) && ...
        isreal(modelNumPredictorsToSample) && isfinite(modelNumPredictorsToSample) && ...
        (modelNumPredictorsToSample == floor(modelNumPredictorsToSample)) && ...
        (modelNumPredictorsToSample > 0), ...
        'validateRandomForestModel:InvalidModelNumPredictorsToSample', ...
        'randomForestModel.numPredictorsToSample must be a positive integer.');

    assert(modelNumPredictorsToSample <= d, ...
        'validateRandomForestModel:ModelNumPredictorsToSampleTooLarge', ...
        'randomForestModel.numPredictorsToSample must not exceed size(trainingData.X, 2).');

    %--------------------------------------%
    % Equality to requested hyperparameters %
    %--------------------------------------%
    assert(modelNumTrees == numTrees, ...
        'validateRandomForestModel:NumTreesMismatch', ...
        ['randomForestModel.numTrees must match ' ...
         'randomForestHyperparameters.numTrees.']);

    assert(modelMinLeafSize == minLeafSize, ...
        'validateRandomForestModel:MinLeafSizeMismatch', ...
        ['randomForestModel.minLeafSize must match ' ...
         'randomForestHyperparameters.minLeafSize.']);

    assert(modelNumPredictorsToSample == numPredictorsToSample, ...
        'validateRandomForestModel:NumPredictorsToSampleMismatch', ...
        ['randomForestModel.numPredictorsToSample must match ' ...
         'randomForestHyperparameters.numPredictorsToSample.']);

    %----------------------------------------%
    % Ensemble prediction interface sanity   %
    %----------------------------------------%
    try
        yHatProbe = predict(ensemble, X);
    catch ME
        error('validateRandomForestModel:EnsemblePredictionFailed', ...
            ['randomForestModel.ensemble failed predict(X) on trainingData.X. ' ...
             'Original error: %s'], ME.message);
    end

    % Accept common MATLAB output types from classification predict
    isSupportedPredictOutput = ...
        isnumeric(yHatProbe) || islogical(yHatProbe) || iscategorical(yHatProbe) || ...
        isstring(yHatProbe) || ischar(yHatProbe) || iscellstr(yHatProbe);

    assert(isSupportedPredictOutput, ...
        'validateRandomForestModel:UnsupportedPredictOutputType', ...
        ['predict(randomForestModel.ensemble, trainingData.X) returned an unsupported ' ...
         'output type for class labels.']);

    assert(numel(yHatProbe) == nTrain, ...
        'validateRandomForestModel:PredictOutputSizeMismatch', ...
        'predict(randomForestModel.ensemble, trainingData.X) must return nTrain predicted labels.');

end