function validatePCATransform(pcaTransform, X)
    % VALIDATEPCATRANSFORM Validates fitted PCA transform.
    %
    % INPUTS
    %  pcaTransform struct with fields:
    %      .mu
    %      .coeff
    %      .explained
    %      .originalDimension
    %      .projectedDimension
    %      .eigenvalues
    %
    %  X (n x d double) - dataset used to fit PCA
    %
    % OUTPUT
    %  None. Throws an error if validation fails.

    % -- Validate X --
    assert(isnumeric(X) && ismatrix(X) && ~isempty(X), ...
        'X must be a nonempty numeric 2D matrix.');

    assert(all(isfinite(X), 'all'), ...
        'X must contain only finite values.');

    [~, d] = size(X);

    % -- Validate top-level pcaTransform --
    assert(isstruct(pcaTransform) && isscalar(pcaTransform), ...
        'pcaTransform must be a scalar struct.');

    requiredFields = { ...
        'mu', ...
        'coeff', ...
        'explained', ...
        'originalDimension', ...
        'projectedDimension', ...
        'eigenvalues' ...
    };

    missingFields = requiredFields(~isfield(pcaTransform, requiredFields));
    assert(isempty(missingFields), ...
        'pcaTransform is missing required field(s): %s.', ...
        strjoin(missingFields, ', '));

    actualFields = fieldnames(pcaTransform);
    assert(numel(actualFields) == numel(requiredFields), ...
        'pcaTransform contains unexpected fields.');

    % -- Validate originalDimension --
    assert(isnumeric(pcaTransform.originalDimension) ...
        && isscalar(pcaTransform.originalDimension) ...
        && isfinite(pcaTransform.originalDimension) ...
        && pcaTransform.originalDimension > 0 ...
        && mod(pcaTransform.originalDimension, 1) == 0, ...
        'pcaTransform.originalDimension must be a positive integer scalar.');

    assert(pcaTransform.originalDimension == d, ...
        ['pcaTransform.originalDimension must match size(X, 2). ' ...
         'Expected %d, got %d.'], d, pcaTransform.originalDimension);

    % -- Validate projectedDimension --
    assert(isnumeric(pcaTransform.projectedDimension) ...
        && isscalar(pcaTransform.projectedDimension) ...
        && isfinite(pcaTransform.projectedDimension) ...
        && pcaTransform.projectedDimension > 0 ...
        && mod(pcaTransform.projectedDimension, 1) == 0, ...
        'pcaTransform.projectedDimension must be a positive integer scalar.');

    k = pcaTransform.projectedDimension;

    assert(k <= d, ...
        ['pcaTransform.projectedDimension cannot exceed original dimension. ' ...
         'Got k = %d and d = %d.'], k, d);

    % -- Validate mu --
    assert(isnumeric(pcaTransform.mu) && isrow(pcaTransform.mu), ...
        'pcaTransform.mu must be a numeric row vector.');

    assert(all(isfinite(pcaTransform.mu)), ...
        'pcaTransform.mu must contain only finite values.');

    assert(numel(pcaTransform.mu) == d, ...
        ['pcaTransform.mu must have length equal to size(X, 2). ' ...
         'Expected length %d, got %d.'], d, numel(pcaTransform.mu));

    % -- Validate coeff --
    assert(isnumeric(pcaTransform.coeff) && ismatrix(pcaTransform.coeff), ...
        'pcaTransform.coeff must be a numeric 2D matrix.');

    assert(all(isfinite(pcaTransform.coeff), 'all'), ...
        'pcaTransform.coeff must contain only finite values.');

    coeffSize = size(pcaTransform.coeff);
    assert(isequal(coeffSize, [d, k]), ...
        ['pcaTransform.coeff must have size (d x k) = (%d x %d). ' ...
         'Got (%d x %d).'], d, k, coeffSize(1), coeffSize(2));

    gramMatrix = pcaTransform.coeff.' * pcaTransform.coeff;
    identityTarget = eye(k);
    orthonormalityTolerance = 1e-8;

    assert(norm(gramMatrix - identityTarget, 'fro') <= orthonormalityTolerance, ...
        'Columns of pcaTransform.coeff must be approximately orthonormal.');

    % -- Validate explained --
    assert(isnumeric(pcaTransform.explained) && isrow(pcaTransform.explained), ...
        'pcaTransform.explained must be a numeric row vector.');

    assert(all(isfinite(pcaTransform.explained)), ...
        'pcaTransform.explained must contain only finite values.');

    assert(numel(pcaTransform.explained) == k, ...
        ['pcaTransform.explained must have length k = %d. ' ...
         'Got %d.'], k, numel(pcaTransform.explained));

    assert(all(pcaTransform.explained >= 0), ...
        'pcaTransform.explained must contain nonnegative values.');

    assert(sum(pcaTransform.explained) <= 100 + 1e-8, ...
        'Sum of pcaTransform.explained cannot exceed 100 by more than numerical tolerance.');

    % -- Validate eigenvalues --
    assert(isnumeric(pcaTransform.eigenvalues) && isrow(pcaTransform.eigenvalues), ...
        'pcaTransform.eigenvalues must be a numeric row vector.');

    assert(all(isfinite(pcaTransform.eigenvalues)), ...
        'pcaTransform.eigenvalues must contain only finite values.');

    assert(numel(pcaTransform.eigenvalues) == k, ...
        ['pcaTransform.eigenvalues must have length k = %d. ' ...
         'Got %d.'], k, numel(pcaTransform.eigenvalues));

    assert(all(pcaTransform.eigenvalues >= 0), ...
        'pcaTransform.eigenvalues must contain nonnegative values.');

    assert(all(diff(pcaTransform.eigenvalues) <= 1e-10), ...
        'pcaTransform.eigenvalues must be sorted in nonincreasing order.');

    assert(all(diff(pcaTransform.explained) <= 1e-10), ...
        'pcaTransform.explained must be sorted in nonincreasing order.');

    zeroEigenvalueTolerance = 1e-12;
    assert(all(pcaTransform.explained(pcaTransform.eigenvalues <= zeroEigenvalueTolerance) <= 1e-8), ...
        ['Components with effectively zero eigenvalue must not have materially ' ...
         'positive explained variance.']);
end