function validatePCASpec(pcaSpec, pcaSpecIndex)
% VALIDATEPCASPEC Validates PCASpec struct and throws error if spec is noncompliant.
% 
% AUTHOR: Cole H. Shaigec
%
% INPUT
%  pcaSpec struct with fields
    assert(isstruct(pcaSpec) && isscalar(pcaSpec), ...
        'Each pcaSpec must be a scalar struct. Failed at index %d.', pcaSpecIndex);

    requiredFields = {'enabled', 'selectionMode', 'varianceThreshold', 'fixedNumComponents'};
    missingFields = requiredFields(~isfield(pcaSpec, requiredFields));

    assert(isempty(missingFields), ...
        'pcaSpec at index %d is missing required field(s): %s.', ...
        pcaSpecIndex, strjoin(missingFields, ', '));

    assert(islogical(pcaSpec.enabled) && isscalar(pcaSpec.enabled), ...
        'pcaSpec(%d).enabled must be a logical scalar.', pcaSpecIndex);

    selectionMode = string(pcaSpec.selectionMode);
    assert(isscalar(selectionMode), ...
        'pcaSpec(%d).selectionMode must be a string scalar or char vector.', pcaSpecIndex);

    validSelectionModes = ["varianceThreshold", "fixedNumComponents"];
    assert(any(selectionMode == validSelectionModes), ...
        ['pcaSpec(%d).selectionMode must be either "varianceThreshold" ' ...
         'or "fixedNumComponents".'], pcaSpecIndex);

    assert(isnumeric(pcaSpec.varianceThreshold) && isscalar(pcaSpec.varianceThreshold) ...
        && isfinite(pcaSpec.varianceThreshold) ...
        && pcaSpec.varianceThreshold >= 0 ...
        && pcaSpec.varianceThreshold <= 1, ...
        'pcaSpec(%d).varianceThreshold must be a scalar in [0, 1].', pcaSpecIndex);

    assert(isnumeric(pcaSpec.fixedNumComponents) && isscalar(pcaSpec.fixedNumComponents) ...
        && isfinite(pcaSpec.fixedNumComponents) ...
        && pcaSpec.fixedNumComponents >= 0 ...
        && mod(pcaSpec.fixedNumComponents, 1) == 0, ...
        'pcaSpec(%d).fixedNumComponents must be a nonnegative integer scalar.', pcaSpecIndex);

    if pcaSpec.enabled
        if selectionMode == "varianceThreshold"
            assert(pcaSpec.varianceThreshold > 0, ...
                'pcaSpec(%d).varianceThreshold must be positive when PCA is enabled and selectionMode is varianceThreshold.', ...
                pcaSpecIndex);
        elseif selectionMode == "fixedNumComponents"
            assert(pcaSpec.fixedNumComponents > 0, ...
                'pcaSpec(%d).fixedNumComponents must be positive when PCA is enabled and selectionMode is fixedNumComponents.', ...
                pcaSpecIndex);
        end
    end
end