function validateGradientBoostingRegressionResult( ...
    gradientBoostingRegressionResult, ...
    dataset, ...
    gradientBoostingRegressionModel)
    % VALIDATEGRADIENTBOOSTINGREGRESSIONRESULT Validates gradient boosting regression prediction result struct.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  gradientBoostingRegressionResult (struct)
    %  dataset (struct)
    %  gradientBoostingRegressionModel (struct)
    %
    % OUTPUTS
    %  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(gradientBoostingRegressionResult), ...
        'validateGradientBoostingRegressionResult:ResultMustBeStruct', ...
        'gradientBoostingRegressionResult must be a struct.');

    assert(isstruct(dataset), ...
        'validateGradientBoostingRegressionResult:DatasetMustBeStruct', ...
        'dataset must be a struct.');

    assert(isstruct(gradientBoostingRegressionModel), ...
        'validateGradientBoostingRegressionResult:ModelMustBeStruct', ...
        'gradientBoostingRegressionModel must be a struct.');

    %---------------------------%
    % dataset validation        %
    %---------------------------%
    requiredDatasetFields = {'X', 'y'};
    assert(all(isfield(dataset, requiredDatasetFields)), ...
        'validateGradientBoostingRegressionResult:MissingDatasetFields', ...
        'dataset must contain fields: X, y.');

    X = dataset.X;
    y = dataset.y;

    assert(isdouble(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateGradientBoostingRegressionResult:InvalidDatasetX', ...
        'dataset.X must be a finite full double matrix.');

    assert(isdouble(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateGradientBoostingRegressionResult:InvalidDatasetY', ...
        'dataset.y must be a finite full double column vector.');

    n = size(X, 1);
    assert(size(y, 1) == n, ...
        'validateGradientBoostingRegressionResult:DatasetDimensionMismatch', ...
        'dataset.X and dataset.y must have the same number of rows.');

    %---------------------------%
    % model validation          %
    %---------------------------%
    requiredModelFields = {'ensemble', 'T', 'learningRate', 'maxNumSplits'};
    assert(all(isfield(gradientBoostingRegressionModel, requiredModelFields)), ...
        'validateGradientBoostingRegressionResult:MissingModelFields', ...
        'gradientBoostingRegressionModel must contain fields: ensemble, T, learningRate, maxNumSplits.');

    ensemble = gradientBoostingRegressionModel.ensemble;
    modelT = gradientBoostingRegressionModel.T;
    modelLearningRate = gradientBoostingRegressionModel.learningRate;
    modelMaxNumSplits = gradientBoostingRegressionModel.maxNumSplits;

    assert(~isempty(ensemble), ...
        'validateGradientBoostingRegressionResult:EmptyEnsemble', ...
        'gradientBoostingRegressionModel.ensemble must be nonempty.');

    assert(isa(ensemble, 'CompactRegressionEnsemble') || isa(ensemble, 'RegressionEnsemble'), ...
        'validateGradientBoostingRegressionResult:InvalidEnsembleClass', ...
        'gradientBoostingRegressionModel.ensemble must be a CompactRegressionEnsemble or RegressionEnsemble.');

    assert(isnumeric(modelT) && isscalar(modelT) && isreal(modelT) && isfinite(modelT) && ...
           (modelT == floor(modelT)) && (modelT > 0), ...
        'validateGradientBoostingRegressionResult:InvalidModelT', ...
        'gradientBoostingRegressionModel.T must be a positive integer.');

    assert(isnumeric(modelLearningRate) && isscalar(modelLearningRate) && ...
           isreal(modelLearningRate) && isfinite(modelLearningRate) && ...
           (modelLearningRate > 0), ...
        'validateGradientBoostingRegressionResult:InvalidModelLearningRate', ...
        'gradientBoostingRegressionModel.learningRate must be a positive finite scalar.');

    assert(isnumeric(modelMaxNumSplits) && isscalar(modelMaxNumSplits) && ...
           isreal(modelMaxNumSplits) && isfinite(modelMaxNumSplits) && ...
           (modelMaxNumSplits == floor(modelMaxNumSplits)) && ...
           (modelMaxNumSplits > 0), ...
        'validateGradientBoostingRegressionResult:InvalidModelMaxNumSplits', ...
        'gradientBoostingRegressionModel.maxNumSplits must be a positive integer.');

    %---------------------------%
    % result field validation   %
    %---------------------------%
    requiredResultFields = {'yHat', 'metadata'};
    assert(all(isfield(gradientBoostingRegressionResult, requiredResultFields)), ...
        'validateGradientBoostingRegressionResult:MissingResultFields', ...
        'gradientBoostingRegressionResult must contain fields: yHat, metadata.');

    yHat = gradientBoostingRegressionResult.yHat;
    metadata = gradientBoostingRegressionResult.metadata;

    assert(isdouble(yHat) && iscolumn(yHat) && ~issparse(yHat) && all(isfinite(yHat)), ...
        'validateGradientBoostingRegressionResult:InvalidYHat', ...
        'gradientBoostingRegressionResult.yHat must be a finite double column vector.');

    assert(size(yHat, 1) == n, ...
        'validateGradientBoostingRegressionResult:YHatSizeMismatch', ...
        'gradientBoostingRegressionResult.yHat must have size n x 1 where n = size(dataset.X, 1).');

    assert(isstruct(metadata) && isscalar(metadata), ...
        'validateGradientBoostingRegressionResult:InvalidMetadata', ...
        'gradientBoostingRegressionResult.metadata must be a scalar struct.');

    %---------------------------%
    % metadata validation       %
    %---------------------------%
    requiredMetadataFields = {'T', 'learningRate', 'maxNumSplits'};
    assert(all(isfield(metadata, requiredMetadataFields)), ...
        'validateGradientBoostingRegressionResult:MissingMetadataFields', ...
        'gradientBoostingRegressionResult.metadata must contain fields: T, learningRate, maxNumSplits.');

    metadataT = metadata.T;
    metadataLearningRate = metadata.learningRate;
    metadataMaxNumSplits = metadata.maxNumSplits;

    assert(isnumeric(metadataT) && isscalar(metadataT) && isreal(metadataT) && ...
           isfinite(metadataT) && (metadataT == floor(metadataT)) && (metadataT > 0), ...
        'validateGradientBoostingRegressionResult:InvalidMetadataT', ...
        'metadata.T must be a positive integer.');

    assert(isnumeric(metadataLearningRate) && isscalar(metadataLearningRate) && ...
           isreal(metadataLearningRate) && isfinite(metadataLearningRate) && ...
           (metadataLearningRate > 0), ...
        'validateGradientBoostingRegressionResult:InvalidMetadataLearningRate', ...
        'metadata.learningRate must be a positive finite scalar.');

    assert(isnumeric(metadataMaxNumSplits) && isscalar(metadataMaxNumSplits) && ...
           isreal(metadataMaxNumSplits) && isfinite(metadataMaxNumSplits) && ...
           (metadataMaxNumSplits == floor(metadataMaxNumSplits)) && ...
           (metadataMaxNumSplits > 0), ...
        'validateGradientBoostingRegressionResult:InvalidMetadataMaxNumSplits', ...
        'metadata.maxNumSplits must be a positive integer.');

    %--------------------------------------%
    % Metadata / model consistency checks  %
    %--------------------------------------%
    assert(metadataT == modelT, ...
        'validateGradientBoostingRegressionResult:MetadataTMismatch', ...
        'metadata.T must match gradientBoostingRegressionModel.T.');

    assert(metadataLearningRate == modelLearningRate, ...
        'validateGradientBoostingRegressionResult:MetadataLearningRateMismatch', ...
        'metadata.learningRate must match gradientBoostingRegressionModel.learningRate.');

    assert(metadataMaxNumSplits == modelMaxNumSplits, ...
        'validateGradientBoostingRegressionResult:MetadataMaxNumSplitsMismatch', ...
        'metadata.maxNumSplits must match gradientBoostingRegressionModel.maxNumSplits.');

    %--------------------------------------%
    % Verify ensemble prediction interface %
    %--------------------------------------%
    try
        yHatProbe = predict(ensemble, X);
    catch ME
        error('validateGradientBoostingRegressionResult:EnsemblePredictionFailed', ...
            ['gradientBoostingRegressionModel.ensemble failed predict(X) on dataset.X. ' ...
             'Original error: %s'], ME.message);
    end

    assert(isnumeric(yHatProbe) && iscolumn(yHatProbe) && size(yHatProbe, 1) == n, ...
        'validateGradientBoostingRegressionResult:InvalidPredictOutputShape', ...
        'predict(gradientBoostingRegressionModel.ensemble, dataset.X) must return an n x 1 vector.');

end