function validateGradientBoostingRegressionModel( ...
    gradientBoostingRegressionModel, ...
    trainingData, ...
    gradientBoostingRegressionHyperparameters)
    % VALIDATEGRADIENTBOOSTINGREGRESSIONMODEL Validates trained gradient boosting regression model struct.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  gradientBoostingRegressionModel (struct)
    %  trainingData (struct)
    %  gradientBoostingRegressionHyperparameters (struct)
    %
    % OUTPUTS
    %  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(gradientBoostingRegressionModel), ...
        'validateGradientBoostingRegressionModel:ModelMustBeStruct', ...
        'gradientBoostingRegressionModel must be a struct.');

    assert(isstruct(trainingData), ...
        'validateGradientBoostingRegressionModel:TrainingDataMustBeStruct', ...
        'trainingData must be a struct.');

    assert(isstruct(gradientBoostingRegressionHyperparameters), ...
        'validateGradientBoostingRegressionModel:HyperparametersMustBeStruct', ...
        'gradientBoostingRegressionHyperparameters must be a struct.');

    %---------------------------%
    % trainingData validation   %
    %---------------------------%
    requiredTrainingFields = {'X', 'y'};
    assert(all(isfield(trainingData, requiredTrainingFields)), ...
        'validateGradientBoostingRegressionModel:MissingTrainingDataFields', ...
        'trainingData must contain fields: X, y.');

    X = trainingData.X;
    y = trainingData.y;

    assert(isdouble(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateGradientBoostingRegressionModel:InvalidTrainingX', ...
        'trainingData.X must be a finite full double matrix.');

    assert(isdouble(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateGradientBoostingRegressionModel:InvalidTrainingY', ...
        'trainingData.y must be a finite full double column vector.');

    nTrain = size(X, 1);
    assert(size(y, 1) == nTrain, ...
        'validateGradientBoostingRegressionModel:TrainingDimensionMismatch', ...
        'trainingData.X and trainingData.y must have the same number of rows.');

    %--------------------------------------%
    % Hyperparameter struct field checking %
    %--------------------------------------%
    requiredHyperparameterFields = {'T', 'learningRate', 'maxNumSplits'};
    assert(all(isfield(gradientBoostingRegressionHyperparameters, requiredHyperparameterFields)), ...
        'validateGradientBoostingRegressionModel:MissingHyperparameterFields', ...
        'gradientBoostingRegressionHyperparameters must contain fields: T, learningRate, maxNumSplits.');

    T = gradientBoostingRegressionHyperparameters.T;
    learningRate = gradientBoostingRegressionHyperparameters.learningRate;
    maxNumSplits = gradientBoostingRegressionHyperparameters.maxNumSplits;

    assert(isnumeric(T) && isscalar(T) && isreal(T) && isfinite(T) && ...
           (T == floor(T)) && (T > 0), ...
        'validateGradientBoostingRegressionModel:InvalidT', ...
        'gradientBoostingRegressionHyperparameters.T must be a positive integer.');

    assert(isnumeric(learningRate) && isscalar(learningRate) && isreal(learningRate) && ...
           isfinite(learningRate) && (learningRate > 0), ...
        'validateGradientBoostingRegressionModel:InvalidLearningRate', ...
        'gradientBoostingRegressionHyperparameters.learningRate must be a positive finite scalar.');

    assert(isnumeric(maxNumSplits) && isscalar(maxNumSplits) && isreal(maxNumSplits) && ...
           isfinite(maxNumSplits) && (maxNumSplits == floor(maxNumSplits)) && ...
           (maxNumSplits > 0), ...
        'validateGradientBoostingRegressionModel:InvalidMaxNumSplits', ...
        'gradientBoostingRegressionHyperparameters.maxNumSplits must be a positive integer.');

    %---------------------------%
    % Model field validation    %
    %---------------------------%
    requiredModelFields = {'ensemble', 'T', 'learningRate', 'maxNumSplits'};
    assert(all(isfield(gradientBoostingRegressionModel, requiredModelFields)), ...
        'validateGradientBoostingRegressionModel:MissingModelFields', ...
        'gradientBoostingRegressionModel must contain fields: ensemble, T, learningRate, maxNumSplits.');

    ensemble = gradientBoostingRegressionModel.ensemble;
    modelT = gradientBoostingRegressionModel.T;
    modelLearningRate = gradientBoostingRegressionModel.learningRate;
    modelMaxNumSplits = gradientBoostingRegressionModel.maxNumSplits;

    %----------------------------------------%
    % Ensemble object / prediction interface %
    %----------------------------------------%
    assert(~isempty(ensemble), ...
        'validateGradientBoostingRegressionModel:EmptyEnsemble', ...
        'gradientBoostingRegressionModel.ensemble must be nonempty.');

    assert(isa(ensemble, 'CompactRegressionEnsemble') || isa(ensemble, 'RegressionEnsemble'), ...
        'validateGradientBoostingRegressionModel:InvalidEnsembleClass', ...
        'gradientBoostingRegressionModel.ensemble must be a CompactRegressionEnsemble or RegressionEnsemble.');

    % Verify the ensemble can predict on the provided training feature dimension.
    try
        yHatProbe = predict(ensemble, X); %#ok<NASGU>
    catch ME
        error('validateGradientBoostingRegressionModel:EnsemblePredictionFailed', ...
            ['gradientBoostingRegressionModel.ensemble failed predict(X) on trainingData.X. ' ...
             'Original error: %s'], ME.message);
    end

    %----------------------------------------%
    % Echoed hyperparameter contract checks  %
    %----------------------------------------%
    assert(isnumeric(modelT) && isscalar(modelT) && isreal(modelT) && isfinite(modelT) && ...
           (modelT == floor(modelT)) && (modelT > 0), ...
        'validateGradientBoostingRegressionModel:InvalidModelT', ...
        'gradientBoostingRegressionModel.T must be a positive integer.');

    assert(isnumeric(modelLearningRate) && isscalar(modelLearningRate) && ...
           isreal(modelLearningRate) && isfinite(modelLearningRate) && ...
           (modelLearningRate > 0), ...
        'validateGradientBoostingRegressionModel:InvalidModelLearningRate', ...
        'gradientBoostingRegressionModel.learningRate must be a positive finite scalar.');

    assert(isnumeric(modelMaxNumSplits) && isscalar(modelMaxNumSplits) && ...
           isreal(modelMaxNumSplits) && isfinite(modelMaxNumSplits) && ...
           (modelMaxNumSplits == floor(modelMaxNumSplits)) && ...
           (modelMaxNumSplits > 0), ...
        'validateGradientBoostingRegressionModel:InvalidModelMaxNumSplits', ...
        'gradientBoostingRegressionModel.maxNumSplits must be a positive integer.');

    %--------------------------------------%
    % Equality to requested hyperparameters %
    %--------------------------------------%
    assert(modelT == T, ...
        'validateGradientBoostingRegressionModel:TMismatch', ...
        'gradientBoostingRegressionModel.T must match gradientBoostingRegressionHyperparameters.T.');

    assert(modelLearningRate == learningRate, ...
        'validateGradientBoostingRegressionModel:LearningRateMismatch', ...
        'gradientBoostingRegressionModel.learningRate must match gradientBoostingRegressionHyperparameters.learningRate.');

    assert(modelMaxNumSplits == maxNumSplits, ...
        'validateGradientBoostingRegressionModel:MaxNumSplitsMismatch', ...
        'gradientBoostingRegressionModel.maxNumSplits must match gradientBoostingRegressionHyperparameters.maxNumSplits.');

end