function validateQDAResult(qdaResult, dataset, qdaModel)
    % VALIDATEQDARESULT Validates regularized binary QDA prediction result struct.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  qdaResult (struct)
    %  dataset (struct)
    %  qdaModel (struct)
    %
    % OUTPUTS
    %  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(qdaResult), ...
        'validateQDAResult:ResultMustBeStruct', ...
        'qdaResult must be a struct.');

    assert(isstruct(dataset), ...
        'validateQDAResult:DatasetMustBeStruct', ...
        'dataset must be a struct.');

    assert(isstruct(qdaModel), ...
        'validateQDAResult:ModelMustBeStruct', ...
        'qdaModel must be a struct.');

    %---------------------------%
    % dataset validation        %
    %---------------------------%
    requiredDatasetFields = {'X', 'y'};
    assert(all(isfield(dataset, requiredDatasetFields)), ...
        'validateQDAResult:MissingDatasetFields', ...
        'dataset must contain fields: X and y.');

    X = dataset.X;
    y = dataset.y;

    assert(isnumeric(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateQDAResult:InvalidDatasetX', ...
        'dataset.X must be a finite full double matrix.');

    assert(isnumeric(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateQDAResult:InvalidDatasetY', ...
        'dataset.y must be a finite full double column vector.');

    [n, d] = size(X);

    assert(size(y, 1) == n, ...
        'validateQDAResult:DatasetDimensionMismatch', ...
        'dataset.X and dataset.y must have the same number of rows.');

    assert(all(ismember(unique(y), [-1; 1])), ...
        'validateQDAResult:InvalidDatasetLabelSet', ...
        'dataset.y must contain exactly the two class labels [-1; 1].');

    %---------------------------%
    % model validation          %
    %---------------------------%
    requiredModelFields = { ...
        'classLabels', ...
        'classPriors', ...
        'logClassPriors', ...
        'classMeans', ...
        'classCovariances', ...
        'classCovarianceInverses', ...
        'logDetCovariances', ...
        'regularizationStrength'};

    assert(all(isfield(qdaModel, requiredModelFields)), ...
        'validateQDAResult:MissingModelFields', ...
        ['qdaModel must contain fields: classLabels, classPriors, logClassPriors, ' ...
         'classMeans, classCovariances, classCovarianceInverses, logDetCovariances, ' ...
         'regularizationStrength.']);

    classLabels = qdaModel.classLabels;
    classPriors = qdaModel.classPriors;
    logClassPriors = qdaModel.logClassPriors;
    classMeans = qdaModel.classMeans;
    classCovariances = qdaModel.classCovariances;
    classCovarianceInverses = qdaModel.classCovarianceInverses;
    logDetCovariances = qdaModel.logDetCovariances;
    modelRegularizationStrength = qdaModel.regularizationStrength;

    assert(isequal(classLabels, [-1; 1]), ...
        'validateQDAResult:InvalidModelClassLabels', ...
        'qdaModel.classLabels must be exactly [-1; 1].');

    assert(isequal(size(classPriors), [2, 1]) && all(isfinite(classPriors)) && all(classPriors > 0), ...
        'validateQDAResult:InvalidClassPriors', ...
        'qdaModel.classPriors must be a positive finite 2 x 1 double vector.');

    assert(isequal(size(logClassPriors), [2, 1]) && all(isfinite(logClassPriors)), ...
        'validateQDAResult:InvalidLogClassPriors', ...
        'qdaModel.logClassPriors must be a finite 2 x 1 double vector.');

    assert(isequal(size(classMeans), [2, d]) && all(isfinite(classMeans), 'all'), ...
        'validateQDAResult:InvalidClassMeans', ...
        'qdaModel.classMeans must be a finite 2 x d double matrix.');

    assert(iscell(classCovariances) && isequal(size(classCovariances), [2, 1]), ...
        'validateQDAResult:InvalidClassCovariances', ...
        'qdaModel.classCovariances must be a 2 x 1 cell array.');

    assert(iscell(classCovarianceInverses) && isequal(size(classCovarianceInverses), [2, 1]), ...
        'validateQDAResult:InvalidClassCovarianceInverses', ...
        'qdaModel.classCovarianceInverses must be a 2 x 1 cell array.');

    assert(isequal(size(logDetCovariances), [2, 1]) && all(isfinite(logDetCovariances)), ...
        'validateQDAResult:InvalidLogDetCovariances', ...
        'qdaModel.logDetCovariances must be a finite 2 x 1 double vector.');

    assert(isnumeric(modelRegularizationStrength) && isscalar(modelRegularizationStrength) && ...
        isreal(modelRegularizationStrength) && isfinite(modelRegularizationStrength) && ...
        (modelRegularizationStrength >= 0), ...
        'validateQDAResult:InvalidRegularizationStrength', ...
        'qdaModel.regularizationStrength must be a nonnegative finite scalar.');

    for i = 1:2
        Sigma = classCovariances{i};
        SigmaInv = classCovarianceInverses{i};

        assert(isnumeric(Sigma) && isequal(size(Sigma), [d, d]) && all(isfinite(Sigma), 'all'), ...
            'validateQDAResult:InvalidClassCovarianceEntry', ...
            'Each entry of qdaModel.classCovariances must be a finite d x d double matrix.');

        assert(isnumeric(SigmaInv) && isequal(size(SigmaInv), [d, d]) && all(isfinite(SigmaInv), 'all'), ...
            'validateQDAResult:InvalidClassCovarianceInverseEntry', ...
            'Each entry of qdaModel.classCovarianceInverses must be a finite d x d double matrix.');
    end

    %---------------------------%
    % result field validation   %
    %---------------------------%
    requiredResultFields = {'yHat', 'metadata'};
    assert(all(isfield(qdaResult, requiredResultFields)), ...
        'validateQDAResult:MissingResultFields', ...
        'qdaResult must contain fields: yHat and metadata.');

    yHat = qdaResult.yHat;
    metadata = qdaResult.metadata;

    assert(isnumeric(yHat) && iscolumn(yHat) && ~issparse(yHat) && all(isfinite(yHat)), ...
        'validateQDAResult:InvalidYHat', ...
        'qdaResult.yHat must be a finite full double column vector.');

    assert(size(yHat, 1) == n, ...
        'validateQDAResult:YHatSizeMismatch', ...
        'qdaResult.yHat must have size n x 1.');

    assert(all(ismember(yHat, [-1; 1])), ...
        'validateQDAResult:PredictedLabelsMustBeMinusOnePlusOne', ...
        'All entries of qdaResult.yHat must belong to the set {-1, +1}.');

    assert(isstruct(metadata) && isscalar(metadata), ...
        'validateQDAResult:InvalidMetadata', ...
        'qdaResult.metadata must be a scalar struct.');

    %---------------------------%
    % metadata validation       %
    %---------------------------%
    requiredMetadataFields = {'logPosteriorScores', 'classLabels', 'regularizationStrength'};
    assert(all(isfield(metadata, requiredMetadataFields)), ...
        'validateQDAResult:MissingMetadataFields', ...
        ['qdaResult.metadata must contain fields: logPosteriorScores, ' ...
         'classLabels, regularizationStrength.']);

    logPosteriorScores = metadata.logPosteriorScores;
    metadataClassLabels = metadata.classLabels;
    metadataRegularizationStrength = metadata.regularizationStrength;

    assert(isnumeric(logPosteriorScores) && ismatrix(logPosteriorScores) && ...
        ~issparse(logPosteriorScores) && all(isfinite(logPosteriorScores), 'all'), ...
        'validateQDAResult:InvalidLogPosteriorScores', ...
        'metadata.logPosteriorScores must be a finite full double matrix.');

    assert(isequal(size(logPosteriorScores), [n, 2]), ...
        'validateQDAResult:LogPosteriorScoresSizeMismatch', ...
        'metadata.logPosteriorScores must have size n x 2.');

    assert(isnumeric(metadataClassLabels) && iscolumn(metadataClassLabels) && ...
        ~issparse(metadataClassLabels) && all(isfinite(metadataClassLabels)), ...
        'validateQDAResult:InvalidMetadataClassLabels', ...
        'metadata.classLabels must be a finite full double column vector.');

    assert(isequal(metadataClassLabels, [-1; 1]), ...
        'validateQDAResult:MetadataClassLabelsMismatch', ...
        'metadata.classLabels must be exactly [-1; 1].');

    assert(isnumeric(metadataRegularizationStrength) && isscalar(metadataRegularizationStrength) && ...
        isreal(metadataRegularizationStrength) && isfinite(metadataRegularizationStrength) && ...
        (metadataRegularizationStrength >= 0), ...
        'validateQDAResult:InvalidMetadataRegularizationStrength', ...
        'metadata.regularizationStrength must be a nonnegative finite scalar.');

    assert(metadataRegularizationStrength == modelRegularizationStrength, ...
        'validateQDAResult:MetadataRegularizationStrengthMismatch', ...
        'metadata.regularizationStrength must match qdaModel.regularizationStrength.');

    %--------------------------------------%
    % Metadata / model consistency checks  %
    %--------------------------------------%
    assert(isequal(metadataClassLabels, classLabels), ...
        'validateQDAResult:MetadataModelClassLabelMismatch', ...
        'metadata.classLabels must match qdaModel.classLabels.');

    %--------------------------------------%
    % Basic score / prediction consistency %
    %--------------------------------------%
    [~, predictedScoreIndices] = max(logPosteriorScores, [], 2);
    impliedYHat = classLabels(predictedScoreIndices);

    assert(isequal(impliedYHat, yHat), ...
        'validateQDAResult:YHatDoesNotMatchScoreArgmax', ...
        ['qdaResult.yHat must equal the class-label mapping induced by the ' ...
         'rowwise argmax of metadata.logPosteriorScores.']);

end