function validateQDAModel(qdaModel, trainingData, qdaHyperparameters)
    % VALIDATEQDAMODEL Validates trained regularized binary QDA model struct.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  qdaModel (struct)
    %  trainingData (struct)
    %  qdaHyperparameters (struct)
    %
    % OUTPUTS
    %  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(qdaModel), ...
        'validateQDAModel:ModelMustBeStruct', ...
        'qdaModel must be a struct.');

    assert(isstruct(trainingData), ...
        'validateQDAModel:TrainingDataMustBeStruct', ...
        'trainingData must be a struct.');

    assert(isstruct(qdaHyperparameters), ...
        'validateQDAModel:HyperparametersMustBeStruct', ...
        'qdaHyperparameters must be a struct.');

    %---------------------------%
    % trainingData validation   %
    %---------------------------%
    requiredTrainingFields = {'X', 'y'};
    assert(all(isfield(trainingData, requiredTrainingFields)), ...
        'validateQDAModel:MissingTrainingDataFields', ...
        'trainingData must contain fields: X and y.');

    X = trainingData.X;
    y = trainingData.y;

    assert(isdouble(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateQDAModel:InvalidTrainingX', ...
        'trainingData.X must be a finite full double matrix.');

    assert(isdouble(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateQDAModel:InvalidTrainingY', ...
        'trainingData.y must be a finite full double column vector.');

    [nTrain, d] = size(X);

    assert(size(y, 1) == nTrain, ...
        'validateQDAModel:TrainingDimensionMismatch', ...
        'trainingData.X and trainingData.y must have the same number of rows.');

    assert(d >= 1, ...
        'validateQDAModel:EmptyFeatureDimension', ...
        'trainingData.X must contain at least one feature column.');

    uniqueLabels = unique(y);
    assert(isequal(uniqueLabels, [-1; 1]), ...
        'validateQDAModel:InvalidTrainingLabelSet', ...
        'trainingData.y must contain exactly the two class labels [-1; 1].');

    %--------------------------------------%
    % Hyperparameter struct field checking %
    %--------------------------------------%
    requiredHyperparameterFields = {'regularizationStrength'};
    assert(all(isfield(qdaHyperparameters, requiredHyperparameterFields)), ...
        'validateQDAModel:MissingHyperparameterFields', ...
        'qdaHyperparameters must contain field: regularizationStrength.');

    regularizationStrength = qdaHyperparameters.regularizationStrength;

    assert(isnumeric(regularizationStrength) && isscalar(regularizationStrength) && ...
        isreal(regularizationStrength) && isfinite(regularizationStrength) && ...
        (regularizationStrength >= 0), ...
        'validateQDAModel:InvalidRegularizationStrength', ...
        'qdaHyperparameters.regularizationStrength must be a nonnegative finite scalar.');

    %---------------------------%
    % Model field validation    %
    %---------------------------%
    requiredModelFields = { ...
        'classLabels', ...
        'classPriors', ...
        'logClassPriors', ...
        'classMeans', ...
        'classCovariances', ...
        'classCovarianceInverses', ...
        'logDetCovariances', ...
        'regularizationStrength'};

    assert(all(isfield(qdaModel, requiredModelFields)), ...
        'validateQDAModel:MissingModelFields', ...
        ['qdaModel must contain fields: classLabels, classPriors, logClassPriors, ' ...
         'classMeans, classCovariances, classCovarianceInverses, logDetCovariances, ' ...
         'regularizationStrength.']);

    classLabels = qdaModel.classLabels;
    classPriors = qdaModel.classPriors;
    logClassPriors = qdaModel.logClassPriors;
    classMeans = qdaModel.classMeans;
    classCovariances = qdaModel.classCovariances;
    classCovarianceInverses = qdaModel.classCovarianceInverses;
    logDetCovariances = qdaModel.logDetCovariances;
    modelRegularizationStrength = qdaModel.regularizationStrength;

    %---------------------------%
    % classLabels validation    %
    %---------------------------%
    assert(isdouble(classLabels) && iscolumn(classLabels) && ~issparse(classLabels) && ...
        all(isfinite(classLabels)), ...
        'validateQDAModel:InvalidClassLabels', ...
        'qdaModel.classLabels must be a finite full double column vector.');

    assert(isequal(classLabels, [-1; 1]), ...
        'validateQDAModel:ClassLabelsMustBeMinusOnePlusOne', ...
        'qdaModel.classLabels must be exactly [-1; 1].');

    %--------------------------------%
    % classPriors / logPriors checks %
    %--------------------------------%
    assert(isdouble(classPriors) && iscolumn(classPriors) && ~issparse(classPriors) && ...
        all(isfinite(classPriors)), ...
        'validateQDAModel:InvalidClassPriors', ...
        'qdaModel.classPriors must be a finite full double column vector.');

    assert(isequal(size(classPriors), [2, 1]), ...
        'validateQDAModel:ClassPriorsSizeMismatch', ...
        'qdaModel.classPriors must have size 2 x 1.');

    assert(all(classPriors > 0), ...
        'validateQDAModel:NonpositiveClassPriors', ...
        'qdaModel.classPriors must be strictly positive.');

    assert(abs(sum(classPriors) - 1) <= 1e-10, ...
        'validateQDAModel:ClassPriorsDoNotSumToOne', ...
        'qdaModel.classPriors must sum to 1.');

    assert(isdouble(logClassPriors) && iscolumn(logClassPriors) && ~issparse(logClassPriors) && ...
        all(isfinite(logClassPriors)), ...
        'validateQDAModel:InvalidLogClassPriors', ...
        'qdaModel.logClassPriors must be a finite full double column vector.');

    assert(isequal(size(logClassPriors), [2, 1]), ...
        'validateQDAModel:LogClassPriorsSizeMismatch', ...
        'qdaModel.logClassPriors must have size 2 x 1.');

    assert(all(abs(logClassPriors - log(classPriors)) <= 1e-10), ...
        'validateQDAModel:LogClassPriorsMismatch', ...
        'qdaModel.logClassPriors must equal log(qdaModel.classPriors).');

    %---------------------------%
    % classMeans validation     %
    %---------------------------%
    assert(isdouble(classMeans) && ismatrix(classMeans) && ~issparse(classMeans) && ...
        all(isfinite(classMeans), 'all'), ...
        'validateQDAModel:InvalidClassMeans', ...
        'qdaModel.classMeans must be a finite full double matrix.');

    assert(isequal(size(classMeans), [2, d]), ...
        'validateQDAModel:ClassMeansSizeMismatch', ...
        'qdaModel.classMeans must have size 2 x d.');

    %----------------------------------%
    % covariance cell array validation %
    %----------------------------------%
    assert(iscell(classCovariances) && isequal(size(classCovariances), [2, 1]), ...
        'validateQDAModel:InvalidClassCovariances', ...
        'qdaModel.classCovariances must be a 2 x 1 cell array.');

    assert(iscell(classCovarianceInverses) && isequal(size(classCovarianceInverses), [2, 1]), ...
        'validateQDAModel:InvalidClassCovarianceInverses', ...
        'qdaModel.classCovarianceInverses must be a 2 x 1 cell array.');

    assert(isdouble(logDetCovariances) && iscolumn(logDetCovariances) && ~issparse(logDetCovariances) && ...
        all(isfinite(logDetCovariances)), ...
        'validateQDAModel:InvalidLogDetCovariances', ...
        'qdaModel.logDetCovariances must be a finite full double column vector.');

    assert(isequal(size(logDetCovariances), [2, 1]), ...
        'validateQDAModel:LogDetCovariancesSizeMismatch', ...
        'qdaModel.logDetCovariances must have size 2 x 1.');

    symmetryTolerance = 1e-10;
    inverseTolerance = 1e-6;

    for i = 1:2
        Sigma = classCovariances{i};
        SigmaInv = classCovarianceInverses{i};

        assert(isdouble(Sigma) && ismatrix(Sigma) && ~issparse(Sigma) && ...
            all(isfinite(Sigma), 'all') && isequal(size(Sigma), [d, d]), ...
            'validateQDAModel:InvalidClassCovarianceEntry', ...
            'Each entry of qdaModel.classCovariances must be a finite d x d double matrix.');

        assert(isdouble(SigmaInv) && ismatrix(SigmaInv) && ~issparse(SigmaInv) && ...
            all(isfinite(SigmaInv), 'all') && isequal(size(SigmaInv), [d, d]), ...
            'validateQDAModel:InvalidClassCovarianceInverseEntry', ...
            'Each entry of qdaModel.classCovarianceInverses must be a finite d x d double matrix.');

        assert(norm(Sigma - Sigma.', 'fro') <= symmetryTolerance, ...
            'validateQDAModel:CovarianceNotSymmetric', ...
            'Each regularized class covariance matrix must be symmetric.');

        assert(norm(SigmaInv - SigmaInv.', 'fro') <= max(symmetryTolerance, inverseTolerance), ...
            'validateQDAModel:CovarianceInverseNotSymmetric', ...
            'Each stored class covariance inverse must be approximately symmetric.');

        % Positive definiteness / invertibility sanity via Cholesky
        [R, p] = chol(Sigma); %#ok<ASGLU>
        assert(p == 0, ...
            'validateQDAModel:CovarianceNotPositiveDefinite', ...
            'Each regularized class covariance matrix must be positive definite.');

        assert(logDetCovariances(i) > -Inf, ...
            'validateQDAModel:NonfiniteLogDet', ...
            'Each entry of qdaModel.logDetCovariances must be finite.');

        % Inverse consistency check
        identityResidual = norm(Sigma * SigmaInv - eye(d), 'fro');
        assert(identityResidual <= inverseTolerance * max(1, d), ...
            'validateQDAModel:CovarianceInverseMismatch', ...
            ['qdaModel.classCovarianceInverses{i} must be approximately the inverse ' ...
             'of qdaModel.classCovariances{i}.']);

        % Log determinant consistency check
        computedLogDet = log(det(Sigma));
        assert(isfinite(computedLogDet), ...
            'validateQDAModel:ComputedLogDetNotFinite', ...
            'det(qdaModel.classCovariances{i}) must be positive and finite.');

        assert(abs(logDetCovariances(i) - computedLogDet) <= 1e-6 * max(1, abs(computedLogDet)), ...
            'validateQDAModel:LogDetMismatch', ...
            ['Each entry of qdaModel.logDetCovariances must match the log determinant ' ...
             'of the corresponding regularized covariance matrix.']);
    end

    %--------------------------------------%
    % Echoed hyperparameter contract checks %
    %--------------------------------------%
    assert(isnumeric(modelRegularizationStrength) && isscalar(modelRegularizationStrength) && ...
        isreal(modelRegularizationStrength) && isfinite(modelRegularizationStrength) && ...
        (modelRegularizationStrength >= 0), ...
        'validateQDAModel:InvalidModelRegularizationStrength', ...
        'qdaModel.regularizationStrength must be a nonnegative finite scalar.');

    assert(modelRegularizationStrength == regularizationStrength, ...
        'validateQDAModel:RegularizationStrengthMismatch', ...
        ['qdaModel.regularizationStrength must match ' ...
         'qdaHyperparameters.regularizationStrength.']);

    %--------------------------------%
    % Training label compatibility   %
    %--------------------------------%
    assert(isequal(uniqueLabels, classLabels), ...
        'validateQDAModel:ClassLabelSetMismatch', ...
        'qdaModel.classLabels must match unique(trainingData.y).');

end