function F1 = computeF1(yHat, yTrue)
    % COMPUTEF1 Computes macro F1 score for predictions generated by a trained classification model.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  yHat (n x 1 double)  - predicted labels
    %  yTrue (n x 1 double) - true labels
    %
    % OUTPUTS
    %  F1 (double)          - macro F1 score

    % Check for input size mismatch
    assert(numel(yHat) == numel(yTrue), 'predicted and true label vectors must have the same number of elements.')

    % Extract true class labels and counts
    allClassLabels = unique(yTrue);
    numClasses = numel(allClassLabels);

    % Preallocate class-level F1 scores
    classLevelF1Scores = zeros(numClasses, 1);

    % Compute F1 scores for each class
    for i = 1 : numClasses
        currentClass = allClassLabels(i);
        currentClassMask = yTrue == currentClass;
        numTrueSamplesOfCurrentClass = sum(currentClassMask);

        % Compute true positives for current class
        truePositivesCurrentClass = yHat(currentClassMask) == currentClass;
        numTruePositivesCurrentClass = sum(truePositivesCurrentClass);

        % Compute false positives for current class
        falsePositivesCurrentClass = yHat(~currentClassMask) == currentClass;
        numFalsePositivesCurrentClass = sum(falsePositivesCurrentClass);
       
        % Compute precision for current class
        numPredictedPositivesCurrentClass = numTruePositivesCurrentClass + numFalsePositivesCurrentClass;
        if numPredictedPositivesCurrentClass == 0
            precisionCurrentClass = 0;
        else
            precisionCurrentClass = numTruePositivesCurrentClass / numPredictedPositivesCurrentClass;
        end

        % Compute recall for current class
        recallCurrentClass = numTruePositivesCurrentClass / (numTrueSamplesOfCurrentClass);

        % Compute class-level F1 and add to tracker
        if precisionCurrentClass + recallCurrentClass == 0
            F1CurrentClass = 0;
        else
            F1CurrentClass = 2 * precisionCurrentClass * recallCurrentClass / (precisionCurrentClass + recallCurrentClass);
        end
        classLevelF1Scores(i) = F1CurrentClass;
    end

    % Return macro F1 score
    F1 = sum(classLevelF1Scores) / numClasses;
end