function templateRow = buildTemplateSummaryTableRow()
    % BUILDTEMPLATESUMMARYTABLEROW Builds scalar struct containing template row for experiment summary table.
    %
    % AUTHOR: Cole H. Shaigec
    % 
    % OUTPUTS
    %  templateRow struct with fields
    %      .runNumber (double)     
    %      .cmapssSubset (string)
    %      .taskType  (string)   
    %      .windowSize (double)
    %      .warningHorizon (double)
    %      .pcaEnabled (boolean)
    %      .pcaSelectionMode (string)
    %      .pcaVarianceThreshold (double)
    %      .MISSINGNESS____ (boolean) - MISSINGNESS NOT YET ARCHITECTED!
    %      .modelName (string)
    %      .boostingRegressionT (double)
    %      .knnK (double)
    %      .KERNELSVMHYPERPARAMETERS____ - KERNEL SVM NOT YET ARCHITECTED!
    %      .logisticRegressionLambda (double)
    %      .logisticRegressionMaxIter (double)
    %      .logisticRegressionSolver (string)
    %      .NAIVEBAYESHYPERPARAMETERS____ - NAIVE BAYES NOT YET ARCHITECTED!
    %      .RANDOMFORESTHYPERPARAMETERS___ - RANDOM FOREST NOT YET ARCHITECTED!
    %      .ridgeRegressionLambda (double)
    %      .trainAccuracy (double)
    %      .trainF1 (double)
    %      .trainPrecision (double)
    %      .trainRecall (double)
    %      .trainAUC_ROC (double)
    %      .trainRMSE (double)
    %      .trainMAE (double)
    %      .trainR2 (double)
    %      .testAccuracy (double)
    %      .testF1 (double)
    %      .testPrecision (double)
    %      .testRecall (double)
    %      .testAUC_ROC (double)
    %      .testRMSE (double)
    %      .testMAE (double)
    %      .testR2 (double)

    % ---------------------------------------------------------------------
    % Type-appropriate placeholders
    % ---------------------------------------------------------------------
    numericPlaceholder  = NaN;                % For numeric/double fields
    stringPlaceholder   = string(missing);    % For string fields
    logicalPlaceholder  = false;              % For logical/boolean fields
    structPlaceholder   = struct();           % For future hyperparameter structs

    % ---------------------------------------------------------------------
    % Build template row with fixed schema
    % ---------------------------------------------------------------------
    templateRow = struct( ...
        'runNumber', numericPlaceholder, ...
        'cmapssSubset', stringPlaceholder, ...
        'taskType', stringPlaceholder, ...
        'windowSize', numericPlaceholder, ...
        'warningHorizon', numericPlaceholder, ...
        'pcaEnabled', logicalPlaceholder, ...
        'pcaSelectionMode', stringPlaceholder, ...
        'pcaVarianceThreshold', numericPlaceholder, ...
        'MISSINGNESS____', logicalPlaceholder, ...
        'modelName', stringPlaceholder, ...
        'boostingRegressionT', numericPlaceholder, ...
        'knnK', numericPlaceholder, ...
        'KERNELSVMHYPERPARAMETERS____', structPlaceholder, ...
        'logisticRegressionLambda', numericPlaceholder, ...
        'logisticRegressionMaxIter', numericPlaceholder, ...
        'logisticRegressionSolver', stringPlaceholder, ...
        'NAIVEBAYESHYPERPARAMETERS____', structPlaceholder, ...
        'RANDOMFORESTHYPERPARAMETERS___', structPlaceholder, ...
        'ridgeRegressionLambda', numericPlaceholder, ...
        'trainAccuracy', numericPlaceholder, ...
        'trainF1', numericPlaceholder, ...
        'trainPrecision', numericPlaceholder, ...
        'trainRecall', numericPlaceholder, ...
        'trainAUC_ROC', numericPlaceholder, ...
        'trainRMSE', numericPlaceholder, ...
        'trainMAE', numericPlaceholder, ...
        'trainR2', numericPlaceholder, ...
        'testAccuracy', numericPlaceholder, ...
        'testF1', numericPlaceholder, ...
        'testPrecision', numericPlaceholder, ...
        'testRecall', numericPlaceholder, ...
        'testAUC_ROC', numericPlaceholder, ...
        'testRMSE', numericPlaceholder, ...
        'testMAE', numericPlaceholder, ...
        'testR2', numericPlaceholder ...
    );
end