function validateNaiveBayesResult(naiveBayesResult, dataset, naiveBayesModel)
    % VALIDATENAIVEBAYESRESULT Validates Gaussian naive Bayes prediction result struct.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  naiveBayesResult (struct)
    %  dataset (struct)
    %  naiveBayesModel (struct)
    %
    % OUTPUTS
    %  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(naiveBayesResult), ...
        'validateNaiveBayesResult:ResultMustBeStruct', ...
        'naiveBayesResult must be a struct.');

    assert(isstruct(dataset), ...
        'validateNaiveBayesResult:DatasetMustBeStruct', ...
        'dataset must be a struct.');

    assert(isstruct(naiveBayesModel), ...
        'validateNaiveBayesResult:ModelMustBeStruct', ...
        'naiveBayesModel must be a struct.');

    %---------------------------%
    % dataset validation        %
    %---------------------------%
    requiredDatasetFields = {'X', 'y'};
    assert(all(isfield(dataset, requiredDatasetFields)), ...
        'validateNaiveBayesResult:MissingDatasetFields', ...
        'dataset must contain fields: X and y.');

    X = dataset.X;
    y = dataset.y;

    assert(isdouble(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateNaiveBayesResult:InvalidDatasetX', ...
        'dataset.X must be a finite full double matrix.');

    assert(isdouble(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateNaiveBayesResult:InvalidDatasetY', ...
        'dataset.y must be a finite full double column vector.');

    n = size(X, 1);
    d = size(X, 2);

    assert(size(y, 1) == n, ...
        'validateNaiveBayesResult:DatasetDimensionMismatch', ...
        'dataset.X and dataset.y must have the same number of rows.');

    %---------------------------%
    % model validation          %
    %---------------------------%
    requiredModelFields = { ...
        'classLabels', ...
        'classPriors', ...
        'logClassPriors', ...
        'classFeatureMeans', ...
        'classFeatureVariances', ...
        'varianceSmoothing'};

    assert(all(isfield(naiveBayesModel, requiredModelFields)), ...
        'validateNaiveBayesResult:MissingModelFields', ...
        ['naiveBayesModel must contain fields: classLabels, classPriors, ' ...
         'logClassPriors, classFeatureMeans, classFeatureVariances, varianceSmoothing.']);

    classLabels = naiveBayesModel.classLabels;
    classPriors = naiveBayesModel.classPriors;
    logClassPriors = naiveBayesModel.logClassPriors;
    classFeatureMeans = naiveBayesModel.classFeatureMeans;
    classFeatureVariances = naiveBayesModel.classFeatureVariances;
    modelVarianceSmoothing = naiveBayesModel.varianceSmoothing;

    assert(isdouble(classLabels) && iscolumn(classLabels) && ~issparse(classLabels) && ...
        all(isfinite(classLabels)), ...
        'validateNaiveBayesResult:InvalidClassLabels', ...
        'naiveBayesModel.classLabels must be a finite full double column vector.');

    K = numel(classLabels);

    assert(K >= 1, ...
        'validateNaiveBayesResult:EmptyClassLabels', ...
        'naiveBayesModel.classLabels must contain at least one class label.');

    assert(numel(unique(classLabels)) == K, ...
        'validateNaiveBayesResult:DuplicateClassLabels', ...
        'naiveBayesModel.classLabels must contain unique class labels.');

    assert(isdouble(classPriors) && iscolumn(classPriors) && ~issparse(classPriors) && ...
        all(isfinite(classPriors)) && numel(classPriors) == K && all(classPriors > 0), ...
        'validateNaiveBayesResult:InvalidClassPriors', ...
        'naiveBayesModel.classPriors must be a positive finite K x 1 double vector.');

    assert(isdouble(logClassPriors) && iscolumn(logClassPriors) && ~issparse(logClassPriors) && ...
        all(isfinite(logClassPriors)) && numel(logClassPriors) == K, ...
        'validateNaiveBayesResult:InvalidLogClassPriors', ...
        'naiveBayesModel.logClassPriors must be a finite K x 1 double vector.');

    assert(isdouble(classFeatureMeans) && ismatrix(classFeatureMeans) && ~issparse(classFeatureMeans) && ...
        all(isfinite(classFeatureMeans), 'all') && isequal(size(classFeatureMeans), [K, d]), ...
        'validateNaiveBayesResult:InvalidClassFeatureMeans', ...
        'naiveBayesModel.classFeatureMeans must be a finite K x d double matrix.');

    assert(isdouble(classFeatureVariances) && ismatrix(classFeatureVariances) && ...
        ~issparse(classFeatureVariances) && all(isfinite(classFeatureVariances), 'all') && ...
        isequal(size(classFeatureVariances), [K, d]) && all(classFeatureVariances > 0, 'all'), ...
        'validateNaiveBayesResult:InvalidClassFeatureVariances', ...
        ['naiveBayesModel.classFeatureVariances must be a finite strictly positive ' ...
         'K x d double matrix.']);

    assert(isnumeric(modelVarianceSmoothing) && isscalar(modelVarianceSmoothing) && ...
        isreal(modelVarianceSmoothing) && isfinite(modelVarianceSmoothing) && ...
        (modelVarianceSmoothing >= 0), ...
        'validateNaiveBayesResult:InvalidVarianceSmoothing', ...
        'naiveBayesModel.varianceSmoothing must be a nonnegative finite scalar.');

    %---------------------------%
    % result field validation   %
    %---------------------------%
    requiredResultFields = {'yHat', 'metadata'};
    assert(all(isfield(naiveBayesResult, requiredResultFields)), ...
        'validateNaiveBayesResult:MissingResultFields', ...
        'naiveBayesResult must contain fields: yHat and metadata.');

    yHat = naiveBayesResult.yHat;
    metadata = naiveBayesResult.metadata;

    assert(isdouble(yHat) && iscolumn(yHat) && ~issparse(yHat) && all(isfinite(yHat)), ...
        'validateNaiveBayesResult:InvalidYHat', ...
        'naiveBayesResult.yHat must be a finite full double column vector.');

    assert(size(yHat, 1) == n, ...
        'validateNaiveBayesResult:YHatSizeMismatch', ...
        'naiveBayesResult.yHat must have size n x 1.');

    assert(all(ismember(yHat, classLabels)), ...
        'validateNaiveBayesResult:PredictedLabelsNotInModelClassLabels', ...
        'All entries of naiveBayesResult.yHat must belong to naiveBayesModel.classLabels.');

    assert(isstruct(metadata) && isscalar(metadata), ...
        'validateNaiveBayesResult:InvalidMetadata', ...
        'naiveBayesResult.metadata must be a scalar struct.');

    %---------------------------%
    % metadata validation       %
    %---------------------------%
    requiredMetadataFields = {'logPosteriorScores', 'classLabels', 'varianceSmoothing'};
    assert(all(isfield(metadata, requiredMetadataFields)), ...
        'validateNaiveBayesResult:MissingMetadataFields', ...
        ['naiveBayesResult.metadata must contain fields: logPosteriorScores, ' ...
         'classLabels, varianceSmoothing.']);

    logPosteriorScores = metadata.logPosteriorScores;
    metadataClassLabels = metadata.classLabels;
    metadataVarianceSmoothing = metadata.varianceSmoothing;

    assert(isdouble(logPosteriorScores) && ismatrix(logPosteriorScores) && ...
        ~issparse(logPosteriorScores) && all(isfinite(logPosteriorScores), 'all'), ...
        'validateNaiveBayesResult:InvalidLogPosteriorScores', ...
        'metadata.logPosteriorScores must be a finite full double matrix.');

    assert(isequal(size(logPosteriorScores), [n, K]), ...
        'validateNaiveBayesResult:LogPosteriorScoresSizeMismatch', ...
        'metadata.logPosteriorScores must have size n x K.');

    assert(isdouble(metadataClassLabels) && iscolumn(metadataClassLabels) && ...
        ~issparse(metadataClassLabels) && all(isfinite(metadataClassLabels)), ...
        'validateNaiveBayesResult:InvalidMetadataClassLabels', ...
        'metadata.classLabels must be a finite full double column vector.');

    assert(isequal(metadataClassLabels, classLabels), ...
        'validateNaiveBayesResult:MetadataClassLabelsMismatch', ...
        'metadata.classLabels must match naiveBayesModel.classLabels.');

    assert(isnumeric(metadataVarianceSmoothing) && isscalar(metadataVarianceSmoothing) && ...
        isreal(metadataVarianceSmoothing) && isfinite(metadataVarianceSmoothing) && ...
        (metadataVarianceSmoothing >= 0), ...
        'validateNaiveBayesResult:InvalidMetadataVarianceSmoothing', ...
        'metadata.varianceSmoothing must be a nonnegative finite scalar.');

    assert(metadataVarianceSmoothing == modelVarianceSmoothing, ...
        'validateNaiveBayesResult:MetadataVarianceSmoothingMismatch', ...
        'metadata.varianceSmoothing must match naiveBayesModel.varianceSmoothing.');

end