function validateNaiveBayesModel(naiveBayesModel, trainingData, naiveBayesHyperparameters)
    % VALIDATENAIVEBAYESMODEL Validates trained Gaussian naive Bayes model struct.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  naiveBayesModel (struct)
    %  trainingData (struct)
    %  naiveBayesHyperparameters (struct)
    %
    % OUTPUTS
    %  None. Throws error if validation fails.

    %---------------------------%
    % Top-level type validation %
    %---------------------------%
    assert(isstruct(naiveBayesModel), ...
        'validateNaiveBayesModel:ModelMustBeStruct', ...
        'naiveBayesModel must be a struct.');

    assert(isstruct(trainingData), ...
        'validateNaiveBayesModel:TrainingDataMustBeStruct', ...
        'trainingData must be a struct.');

    assert(isstruct(naiveBayesHyperparameters), ...
        'validateNaiveBayesModel:HyperparametersMustBeStruct', ...
        'naiveBayesHyperparameters must be a struct.');

    %---------------------------%
    % trainingData validation   %
    %---------------------------%
    requiredTrainingFields = {'X', 'y'};
    assert(all(isfield(trainingData, requiredTrainingFields)), ...
        'validateNaiveBayesModel:MissingTrainingDataFields', ...
        'trainingData must contain fields: X and y.');

    X = trainingData.X;
    y = trainingData.y;

    assert(isnumeric(X) && ismatrix(X) && ~issparse(X) && all(isfinite(X), 'all'), ...
        'validateNaiveBayesModel:InvalidTrainingX', ...
        'trainingData.X must be a finite full double matrix.');

    assert(isnumeric(y) && iscolumn(y) && ~issparse(y) && all(isfinite(y)), ...
        'validateNaiveBayesModel:InvalidTrainingY', ...
        'trainingData.y must be a finite full double column vector.');

    nTrain = size(X, 1);
    d = size(X, 2);

    assert(size(y, 1) == nTrain, ...
        'validateNaiveBayesModel:TrainingDimensionMismatch', ...
        'trainingData.X and trainingData.y must have the same number of rows.');

    %--------------------------------------%
    % Hyperparameter struct field checking %
    %--------------------------------------%
    requiredHyperparameterFields = {'varianceSmoothing'};
    assert(all(isfield(naiveBayesHyperparameters, requiredHyperparameterFields)), ...
        'validateNaiveBayesModel:MissingHyperparameterFields', ...
        'naiveBayesHyperparameters must contain field: varianceSmoothing.');

    varianceSmoothing = naiveBayesHyperparameters.varianceSmoothing;

    assert(isnumeric(varianceSmoothing) && isscalar(varianceSmoothing) && ...
        isreal(varianceSmoothing) && isfinite(varianceSmoothing) && ...
        (varianceSmoothing >= 0), ...
        'validateNaiveBayesModel:InvalidVarianceSmoothing', ...
        'naiveBayesHyperparameters.varianceSmoothing must be a nonnegative finite scalar.');

    %---------------------------%
    % Model field validation    %
    %---------------------------%
    requiredModelFields = { ...
        'classLabels', ...
        'classPriors', ...
        'logClassPriors', ...
        'classFeatureMeans', ...
        'classFeatureVariances', ...
        'varianceSmoothing'};

    assert(all(isfield(naiveBayesModel, requiredModelFields)), ...
        'validateNaiveBayesModel:MissingModelFields', ...
        ['naiveBayesModel must contain fields: classLabels, classPriors, ' ...
         'logClassPriors, classFeatureMeans, classFeatureVariances, varianceSmoothing.']);

    classLabels = naiveBayesModel.classLabels;
    classPriors = naiveBayesModel.classPriors;
    logClassPriors = naiveBayesModel.logClassPriors;
    classFeatureMeans = naiveBayesModel.classFeatureMeans;
    classFeatureVariances = naiveBayesModel.classFeatureVariances;
    modelVarianceSmoothing = naiveBayesModel.varianceSmoothing;

    %---------------------------%
    % classLabels validation    %
    %---------------------------%
    assert(isnumeric(classLabels) && iscolumn(classLabels) && ~issparse(classLabels) && ...
        all(isfinite(classLabels)), ...
        'validateNaiveBayesModel:InvalidClassLabels', ...
        'naiveBayesModel.classLabels must be a finite full double column vector.');

    K = numel(classLabels);

    assert(K >= 1, ...
        'validateNaiveBayesModel:EmptyClassLabels', ...
        'naiveBayesModel.classLabels must contain at least one class label.');

    assert(numel(unique(classLabels)) == K, ...
        'validateNaiveBayesModel:DuplicateClassLabels', ...
        'naiveBayesModel.classLabels must contain unique class labels.');

    %--------------------------------%
    % classPriors / logPriors checks %
    %--------------------------------%
    assert(isnumeric(classPriors) && iscolumn(classPriors) && ~issparse(classPriors) && ...
        all(isfinite(classPriors)), ...
        'validateNaiveBayesModel:InvalidClassPriors', ...
        'naiveBayesModel.classPriors must be a finite full double column vector.');

    assert(numel(classPriors) == K, ...
        'validateNaiveBayesModel:ClassPriorsSizeMismatch', ...
        'naiveBayesModel.classPriors must have size K x 1.');

    assert(all(classPriors > 0), ...
        'validateNaiveBayesModel:NonpositiveClassPriors', ...
        'naiveBayesModel.classPriors must be strictly positive.');

    assert(abs(sum(classPriors) - 1) <= 1e-10, ...
        'validateNaiveBayesModel:ClassPriorsDoNotSumToOne', ...
        'naiveBayesModel.classPriors must sum to 1.');

    assert(isnumeric(logClassPriors) && iscolumn(logClassPriors) && ~issparse(logClassPriors) && ...
        all(isfinite(logClassPriors)), ...
        'validateNaiveBayesModel:InvalidLogClassPriors', ...
        'naiveBayesModel.logClassPriors must be a finite full double column vector.');

    assert(numel(logClassPriors) == K, ...
        'validateNaiveBayesModel:LogClassPriorsSizeMismatch', ...
        'naiveBayesModel.logClassPriors must have size K x 1.');

    assert(all(abs(logClassPriors - log(classPriors)) <= 1e-10), ...
        'validateNaiveBayesModel:LogClassPriorsMismatch', ...
        'naiveBayesModel.logClassPriors must equal log(naiveBayesModel.classPriors).');

    %----------------------------------%
    % class-conditional statistic size %
    %----------------------------------%
    assert(isnumeric(classFeatureMeans) && ismatrix(classFeatureMeans) && ...
        ~issparse(classFeatureMeans) && all(isfinite(classFeatureMeans), 'all'), ...
        'validateNaiveBayesModel:InvalidClassFeatureMeans', ...
        'naiveBayesModel.classFeatureMeans must be a finite full double matrix.');

    assert(isequal(size(classFeatureMeans), [K, d]), ...
        'validateNaiveBayesModel:ClassFeatureMeansSizeMismatch', ...
        'naiveBayesModel.classFeatureMeans must have size K x d.');

    assert(isnumeric(classFeatureVariances) && ismatrix(classFeatureVariances) && ...
        ~issparse(classFeatureVariances) && all(isfinite(classFeatureVariances), 'all'), ...
        'validateNaiveBayesModel:InvalidClassFeatureVariances', ...
        'naiveBayesModel.classFeatureVariances must be a finite full double matrix.');

    assert(isequal(size(classFeatureVariances), [K, d]), ...
        'validateNaiveBayesModel:ClassFeatureVariancesSizeMismatch', ...
        'naiveBayesModel.classFeatureVariances must have size K x d.');

    assert(all(classFeatureVariances > 0, 'all'), ...
        'validateNaiveBayesModel:NonpositiveClassFeatureVariances', ...
        'naiveBayesModel.classFeatureVariances must be strictly positive elementwise.');

    %--------------------------------------%
    % Echoed hyperparameter contract checks %
    %--------------------------------------%
    assert(isnumeric(modelVarianceSmoothing) && isscalar(modelVarianceSmoothing) && ...
        isreal(modelVarianceSmoothing) && isfinite(modelVarianceSmoothing) && ...
        (modelVarianceSmoothing >= 0), ...
        'validateNaiveBayesModel:InvalidModelVarianceSmoothing', ...
        'naiveBayesModel.varianceSmoothing must be a nonnegative finite scalar.');

    assert(modelVarianceSmoothing == varianceSmoothing, ...
        'validateNaiveBayesModel:VarianceSmoothingMismatch', ...
        ['naiveBayesModel.varianceSmoothing must match ' ...
         'naiveBayesHyperparameters.varianceSmoothing.']);

    %--------------------------------%
    % Training label compatibility   %
    %--------------------------------%
    uniqueTrainingLabels = unique(y);
    assert(numel(uniqueTrainingLabels) == K, ...
        'validateNaiveBayesModel:NumberOfClassesMismatch', ...
        'Number of unique labels in trainingData.y must match numel(naiveBayesModel.classLabels).');

    assert(isequal(uniqueTrainingLabels, classLabels), ...
        'validateNaiveBayesModel:ClassLabelSetMismatch', ...
        'naiveBayesModel.classLabels must match unique(trainingData.y).');

end